#if defined(STM32WB)  // 如果定义了STM32WB系列芯片
#define __HAL_RCC_QSPI_CLK_DISABLE            __HAL_RCC_QUADSPI_CLK_DISABLE  // 禁用QSPI时钟
#define __HAL_RCC_QSPI_CLK_ENABLE             __HAL_RCC_QUADSPI_CLK_ENABLE   // 使能QSPI时钟
#define __HAL_RCC_QSPI_CLK_SLEEP_DISABLE      __HAL_RCC_QUADSPI_CLK_SLEEP_DISABLE  // 睡眠模式下禁用QSPI时钟
#define __HAL_RCC_QSPI_CLK_SLEEP_ENABLE       __HAL_RCC_QUADSPI_CLK_SLEEP_ENABLE   // 睡眠模式下使能QSPI时钟
#define __HAL_RCC_QSPI_FORCE_RESET            __HAL_RCC_QUADSPI_FORCE_RESET  // 强制复位QSPI
#define __HAL_RCC_QSPI_RELEASE_RESET          __HAL_RCC_QUADSPI_RELEASE_RESET  // 释放QSPI复位
#define __HAL_RCC_QSPI_IS_CLK_ENABLED         __HAL_RCC_QUADSPI_IS_CLK_ENABLED  // 检查QSPI时钟是否使能
#define __HAL_RCC_QSPI_IS_CLK_DISABLED        __HAL_RCC_QUADSPI_IS_CLK_DISABLED  // 检查QSPI时钟是否禁用
#define __HAL_RCC_QSPI_IS_CLK_SLEEP_ENABLED   __HAL_RCC_QUADSPI_IS_CLK_SLEEP_ENABLED  // 检查睡眠模式下QSPI时钟是否使能
#define __HAL_RCC_QSPI_IS_CLK_SLEEP_DISABLED  __HAL_RCC_QUADSPI_IS_CLK_SLEEP_DISABLED  // 检查睡眠模式下QSPI时钟是否禁用
#define QSPI_IRQHandler QUADSPI_IRQHandler  // 定义QSPI中断处理函数
#endif /* __HAL_RCC_QUADSPI_CLK_ENABLE */  // 结束条件编译块