#if defined(STM32L0)
/* 对于STM32L0系列，将高速模式宏定义为中等速度模式（出于兼容性考虑） */
#define COMP_MODE_HIGHSPEED              COMP_POWERMODE_MEDIUMSPEED
/* 对于STM32L0系列，将低速模式宏定义为超低功耗模式（出于兼容性考虑） */
#define COMP_MODE_LOWSPEED               COMP_POWERMODE_ULTRALOWPOWER
#else
/* 高速模式宏定义 */
#define COMP_MODE_HIGHSPEED              COMP_POWERMODE_HIGHSPEED
/* 中速模式宏定义 */
#define COMP_MODE_MEDIUMSPEED            COMP_POWERMODE_MEDIUMSPEED
/* 低功耗模式宏定义 */
#define COMP_MODE_LOWPOWER               COMP_POWERMODE_LOWPOWER
/* 超低功耗模式宏定义 */
#define COMP_MODE_ULTRALOWPOWER          COMP_POWERMODE_ULTRALOWPOWER
#endif

#endif  /* 结束条件编译块 */

#if defined(STM32U5)
/* 针对STM32U5系列，修正RASING拼写错误，映射到正确的RISING标志清除宏 */
#define __HAL_COMP_COMP1_EXTI_CLEAR_RASING_FLAG __HAL_COMP_COMP1_EXTI_CLEAR_RISING_FLAG
#endif

/**
  * @}
  */

/** @defgroup HAL_CORTEX_Aliased_Defines 为保持向后兼容性而维护的HAL CORTEX别名定义
  * @{
  */
/* 将旧的系统时钟配置宏映射到新的HAL函数宏 */
#define __HAL_CORTEX_SYSTICKCLK_CONFIG HAL_SYSTICK_CLKSourceConfig
#if defined(STM32U5)
/* 内存保护单元设备属性：非聚集、非重排、非提前写 */
#define  MPU_DEVICE_nGnRnE          MPU_DEVICE_NGNRNE
/* 内存保护单元设备属性：非聚集、非重排、可提前写 */
#define  MPU_DEVICE_nGnRE           MPU_DEVICE_NGNRE
/* 内存保护单元设备属性：非聚集、可重排、可提前写 */
#define  MPU_DEVICE_nGRE            MPU_DEVICE_NGRE
#endif /* STM32U5 */
/**
  * @}
  */

/** @defgroup CRC_Aliases CRC API别名
  * @{
  */
#if defined(STM32H5) || defined(STM32C0)
/* STM32H5和STM32C0系列不使用这些别名 */
#else
/* 将旧的数据输入反转函数映射到新的扩展函数（用于跨STM32系列兼容性） */
#define HAL_CRC_Input_Data_Reverse   HAL_CRCEx_Input_Data_Reverse
/* 将旧的数据输出反转函数映射到新的扩展函数（用于跨STM32系列兼容性） */
#define HAL_CRC_Output_Data_Reverse  HAL_CRCEx_Output_Data_Reverse
#endif
/**
  * @}
  */

/** @defgroup HAL_CRC_Aliased_Defines 为保持向后兼容性而维护的HAL CRC别名定义
  * @{
  */

/* 禁用CRC输出数据反转的旧宏定义 */
#define CRC_OUTPUTDATA_INVERSION_DISABLED    CRC_OUTPUTDATA_INVERSION_DISABLE
/* 启用CRC输出数据反转的旧宏定义 */
#define CRC_OUTPUTDATA_INVERSION_ENABLED     CRC_OUTPUTDATA_INVERSION_ENABLE

/**
  * @}
  */

/** @defgroup HAL_DAC_Aliased_Defines 为保持向后兼容性而维护的HAL DAC别名定义
  * @{
  */

/* DAC通道的旧宏定义 */
#define DAC1_CHANNEL_1                                  DAC_CHANNEL_1
#define DAC1_CHANNEL_2                                  DAC_CHANNEL_2
#define DAC2_CHANNEL_1                                  DAC_CHANNEL_1
/* 无波形生成模式 */
#define DAC_WAVE_NONE                                   0x00000000U
/* 噪声波形生成模式 */
#define DAC_WAVE_NOISE                                  DAC_CR_WAVE1_0
/* 三角波形生成模式 */
#define DAC_WAVE_TRIANGLE                               DAC_CR_WAVE1_1
/* 无波形生成的旧宏定义 */
#define DAC_WAVEGENERATION_NONE                         DAC_WAVE_NONE
/* 噪声波形生成的旧宏定义 */
#define DAC_WAVEGENERATION_NOISE                        DAC_WAVE_NOISE
/* 三角波形生成的旧宏定义 */
#define DAC_WAVEGENERATION_TRIANGLE                     DAC_WAVE_TRIANGLE

#if defined(STM32G4) || defined(STM32H7) || defined (STM32U5)
/* 禁用DAC芯片连接（使用外部连接） */
#define DAC_CHIPCONNECT_DISABLE       DAC_CHIPCONNECT_EXTERNAL
/* 启用DAC芯片连接（使用内部连接） */
#define DAC_CHIPCONNECT_ENABLE        DAC_CHIPCONNECT_INTERNAL
#endif

#if defined(STM32U5)
/* 停止LPTIM1输出的触发源旧宏定义 */
#define DAC_TRIGGER_STOP_LPTIM1_OUT  DAC_TRIGGER_STOP_LPTIM1_CH1
/* 停止LPTIM3输出的触发源旧宏定义 */
#define DAC_TRIGGER_STOP_LPTIM3_OUT  DAC_TRIGGER_STOP_LPTIM3_CH1
/* LPTIM1输出触发源旧宏定义 */
#define DAC_TRIGGER_LPTIM1_OUT       DAC_TRIGGER_LPTIM1_CH1
/* LPTIM3输出触发源旧宏定义 */
#define DAC_TRIGGER_LPTIM3_OUT       DAC_TRIGGER_LPTIM3_CH1
#endif

#if defined(STM32H5)
/* LPTIM1输出触发源旧宏定义 */
#define DAC_TRIGGER_LPTIM1_OUT       DAC_TRIGGER_LPTIM1_CH1
/* LPTIM2输出触发源旧宏定义 */
#define DAC_TRIGGER_LPTIM2_OUT       DAC_TRIGGER_LPTIM2_CH1
#endif

#if defined(STM32L1) || defined(STM32L4) || defined(STM32G0) || defined(STM32L5) || defined(STM32H7) || \
    defined(STM32F4) || defined(STM32G4)
/* DAC MSP初始化回调ID的旧宏定义 */
#define HAL_DAC_MSP_INIT_CB_ID       HAL_DAC_MSPINIT_CB_ID
/* DAC MSP反初始化回调ID的旧宏定义 */
#define HAL_DAC_MSP_DEINIT_CB_ID     HAL_DAC_MSPDEINIT_CB_ID
#endif

/**
  * @}
  */

/** @defgroup HAL_DMA_Aliased_Defines 为保持向后兼容性而维护的HAL DMA别名定义
  * @{
  */
/* DMA重映射通道的旧宏定义 */
#define HAL_REMAPDMA_ADC_DMA_CH2                DMA_REMAP_ADC_DMA_CH2
#define HAL_REMAPDMA_USART1_TX_DMA_CH4          DMA_REMAP_USART1_TX_DMA_CH4
#define HAL_REMAPDMA_USART1_RX_DMA_CH5          DMA_REMAP_USART1_RX_DMA_CH5
#define HAL_REMAPDMA_TIM16_DMA_CH4              DMA_REMAP_TIM16_DMA_CH4
#define HAL_REMAPDMA_TIM17_DMA_CH2              DMA_REMAP_TIM17_DMA_CH2
#define HAL_REMAPDMA_USART3_DMA_CH32            DMA_REMAP_USART3_DMA_CH32
#define HAL_REMAPDMA_TIM16_DMA_CH6              DMA_REMAP_TIM16_DMA_CH6
#define HAL_REMAPDMA_TIM17_DMA_CH7              DMA_REMAP_TIM17_DMA_CH7
#define HAL_REMAPDMA_SPI2_DMA_CH67              DMA_REMAP_SPI2_DMA_CH67
#define HAL_REMAPDMA_USART2_DMA_CH67            DMA_REMAP_USART2_DMA_CH67
#define HAL_REMAPDMA_I2C1_DMA_CH76              DMA_REMAP_I2C1_DMA_CH76
#define HAL_REMAPDMA_TIM1_DMA_CH6               DMA_REMAP_TIM1_DMA_CH6
#define HAL_REMAPDMA_TIM2_DMA_CH7               DMA_REMAP_TIM2_DMA_CH7
#define HAL_REMAPDMA_TIM3_DMA_CH6               DMA_REMAP_TIM3_DMA_CH6

/* DMA重映射检查宏的旧定义 */
#define IS_HAL_REMAPDMA                          IS_DMA_REMAP
/* 启用DMA重映射通道的旧宏定义 */
#define __HAL_REMAPDMA_CHANNEL_ENABLE            __HAL_DMA_REMAP_CHANNEL_ENABLE
/* 禁用DMA重映射通道的旧宏定义 */
#define __HAL_REMAPDMA_CHANNEL_DISABLE           __HAL_DMA_REMAP_CHANNEL_DISABLE

#if defined(STM32L4)

/* DMAMUX1请求生成事件源的旧宏定义 */
#define HAL_DMAMUX1_REQUEST_GEN_EXTI0            HAL_DMAMUX1_REQ_GEN_EXTI0
#define HAL_DMAMUX1_REQUEST_GEN_EXTI1            HAL_DMAMUX1_REQ_GEN_EXTI1
#define HAL_DMAMUX1_REQUEST_GEN_EXTI2            HAL_DMAMUX1_REQ_GEN_EXTI2
#define HAL_DMAMUX1_REQUEST_GEN_EXTI3            HAL_DMAMUX1_REQ_GEN_EXTI3
#define HAL_DMAMUX1_REQUEST_GEN_EXTI4            HAL_DMAMUX1_REQ_GEN_EXTI4
#define HAL_DMAMUX1_REQUEST_GEN_EXTI5            HAL_DMAMUX1_REQ_GEN_EXTI5
#define HAL_DMAMUX1_REQUEST_GEN_EXTI6            HAL_DMAMUX1_REQ_GEN_EXTI6
#define HAL_DMAMUX1_REQUEST_GEN_EXTI7            HAL_DMAMUX1_REQ_GEN_EXTI7
#define HAL_DMAMUX1_REQUEST_GEN_EXTI8            HAL_DMAMUX1_REQ_GEN_EXTI8
#define HAL_DMAMUX1_REQUEST_GEN_EXTI9            HAL_DMAMUX1_REQ_GEN_EXTI9
#define HAL_DMAMUX1_REQUEST_GEN_EXTI10           HAL_DMAMUX1_REQ_GEN_EXTI10
#define HAL_DMAMUX1_REQUEST_GEN_EXTI11           HAL_DMAMUX1_REQ_GEN_EXTI11
#define HAL_DMAMUX1_REQUEST_GEN_EXTI12           HAL_DMAMUX1_REQ_GEN_EXTI12
#define HAL_DMAMUX1_REQUEST_GEN_EXTI13           HAL_DMAMUX1_REQ_GEN_EXTI13
#define HAL_DMAMUX1_REQUEST_GEN_EXTI14           HAL_DMAMUX1_REQ_GEN_EXTI14
#define HAL_DMAMUX1_REQUEST_GEN_EXTI15           HAL_DMAMUX1_REQ_GEN_EXTI15
#define HAL_DMAMUX1_REQUEST_GEN_DMAMUX1_CH0_EVT  HAL_DMAMUX1_REQ_GEN_DMAMUX1_CH0_EVT
#define HAL_DMAMUX1_REQUEST_GEN_DMAMUX1_CH1_EVT  HAL_DMAMUX1_REQ_GEN_DMAMUX1_CH1_EVT
#define HAL_DMAMUX1_REQUEST_GEN_DMAMUX1_CH2_EVT  HAL_DMAMUX1_REQ_GEN_DMAMUX1_CH2_EVT
#define HAL_DMAMUX1_REQUEST_GEN_DMAMUX1_CH3_EVT  HAL_DMAMUX1_REQ_GEN_DMAMUX1_CH3_EVT
#define HAL_DMAMUX1_REQUEST_GEN_LPTIM1_OUT       HAL_DMAMUX1_REQ_GEN_LPTIM1_OUT
#define HAL_DMAMUX1_REQUEST_GEN_LPTIM2_OUT       HAL_DMAMUX1_REQ_GEN_LPTIM2_OUT
#define HAL_DMAMUX1_REQUEST_GEN_DSI_TE           HAL_DMAMUX1_REQ_GEN_DSI_TE
#define HAL_DMAMUX1_REQUEST_GEN_DSI_EOT          HAL_DMAMUX1_REQ_GEN_DSI_EOT
#define HAL_DMAMUX1_REQUEST_GEN_DMA2D_EOT        HAL_DMAMUX1_REQ_GEN_DMA2D_EOT
#define HAL_DMAMUX1_REQUEST_GEN_LTDC_IT          HAL_DMAMUX1_REQ_GEN_LTDC_IT

/* DMAMUX请求生成事件的旧宏定义 */
#define HAL_DMAMUX_REQUEST_GEN_NO_EVENT          HAL_DMAMUX_REQ_GEN_NO_EVENT
#define HAL_DMAMUX_REQUEST_GEN_RISING            HAL_DMAMUX_REQ_GEN_RISING
#define HAL_DMAMUX_REQUEST_GEN_FALLING           HAL_DMAMUX_REQ_GEN_FALLING
#define HAL_DMAMUX_REQUEST_GEN_RISING_FALLING    HAL_DMAMUX_REQ_GEN_RISING_FALLING

#if defined(STM32L4R5xx) || defined(STM32L4R9xx) || defined(STM32L4R9xx) || defined(STM32L4S5xx) || \
    defined(STM32L4S7xx) || defined(STM32L4S9xx)
/* DCMI/PSSI DMA请求的旧宏定义 */
#define DMA_REQUEST_DCMI_PSSI                    DMA_REQUEST_DCMI
#endif

#endif /* STM32L4 */

#if defined(STM32G0)
/* DAC1通道1 DMA请求的旧宏定义 */
#define DMA_REQUEST_DAC1_CHANNEL1                DMA_REQUEST_DAC1_CH1
/* DAC1通道2 DMA请求的旧宏定义 */
#define DMA_REQUEST_DAC1_CHANNEL2                DMA_REQUEST_DAC1_CH2
/* TIM16触发/COM DMA请求的旧宏定义 */
#define DMA_REQUEST_TIM16_TRIG_COM               DMA_REQUEST_TIM16_COM
/* TIM17触发/COM DMA请求的旧宏定义 */
#define DMA_REQUEST_TIM17_TRIG_COM               DMA_REQUEST_TIM17_COM

/* LL库中TIM16触发/COM DMAMUX请求的旧宏定义 */
#define LL_DMAMUX_REQ_TIM16_TRIG_COM             LL_DMAMUX_REQ_TIM16_COM
/* LL库中TIM17触发/COM DMAMUX请求的旧宏定义 */
#define LL_DMAMUX_REQ_TIM17_TRIG_COM             LL_DMAMUX_REQ_TIM17_COM
#endif

#if defined(STM32H7)

/* DAC1 DMA请求的旧宏定义 */
#define DMA_REQUEST_DAC1 DMA_REQUEST_DAC1_CH1
/* DAC2 DMA请求的旧宏定义 */
#define DMA_REQUEST_DAC2 DMA_REQUEST_DAC1_CH2

/* LPUART1 RX BDMA请求的旧宏定义 */
#define BDMA_REQUEST_LP_UART1_RX BDMA_REQUEST_LPUART1_RX
/* LPUART1 TX BDMA请求的旧宏定义 */
#define BDMA_REQUEST_LP_UART1_TX BDMA_REQUEST_LPUART1_TX

/* DMAMUX1请求生成事件源的旧宏定义 */
#define HAL_DMAMUX1_REQUEST_GEN_DMAMUX1_CH0_EVT    HAL_DMAMUX1_REQ_GEN_DMAMUX1_CH0_EVT
#define HAL_DMAMUX1_REQUEST_GEN_DMAMUX1_CH1_EVT    HAL_DMAMUX1_REQ_GEN_DMAMUX1_CH1_EVT
#define HAL_DMAMUX1_REQUEST_GEN_DMAMUX1_CH2_EVT    HAL_DMAMUX1_REQ_GEN_DMAMUX1_CH2_EVT
#define HAL_DMAMUX1_REQUEST_GEN_LPTIM1_OUT         HAL_DMAMUX1_REQ_GEN_LPTIM1_OUT
#define HAL_DMAMUX1_REQUEST_GEN_LPTIM2_OUT         HAL_DMAMUX1_REQ_GEN_LPTIM2_OUT
#define HAL_DMAMUX1_REQUEST_GEN_LPTIM3_OUT         HAL_DMAMUX1_REQ_GEN_LPTIM3_OUT
#define HAL_DMAMUX1_REQUEST_GEN_EXTI0              HAL_DMAMUX1_REQ_GEN_EXTI0
#define HAL_DMAMUX1_REQUEST_GEN_TIM12_TRGO         HAL_DMAMUX1_REQ_GEN_TIM12_TRGO