#if defined(STM32H7)  /* 如果定义了STM32H7，则编译以下宏定义 */
#define __HAL_RCC_WWDG_CLK_DISABLE   __HAL_RCC_WWDG1_CLK_DISABLE  /* 禁用WWDG时钟 */
#define __HAL_RCC_WWDG_CLK_ENABLE   __HAL_RCC_WWDG1_CLK_ENABLE    /* 使能WWDG时钟 */
#define __HAL_RCC_WWDG_CLK_SLEEP_DISABLE  __HAL_RCC_WWDG1_CLK_SLEEP_DISABLE  /* 在睡眠模式下禁用WWDG时钟 */
#define __HAL_RCC_WWDG_CLK_SLEEP_ENABLE  __HAL_RCC_WWDG1_CLK_SLEEP_ENABLE    /* 在睡眠模式下使能WWDG时钟 */

#define __HAL_RCC_WWDG_FORCE_RESET    ((void)0U)  /* 在STM32H7上不可用 */
#define __HAL_RCC_WWDG_RELEASE_RESET ((void)0U) /* 在STM32H7上不可用 */


#define  __HAL_RCC_WWDG_IS_CLK_ENABLED    __HAL_RCC_WWDG1_IS_CLK_ENABLED    /* 检查WWDG时钟是否使能 */
#define  __HAL_RCC_WWDG_IS_CLK_DISABLED  __HAL_RCC_WWDG1_IS_CLK_DISABLED    /* 检查WWDG时钟是否禁用 */
#define  RCC_SPI4CLKSOURCE_D2PCLK1       RCC_SPI4CLKSOURCE_D2PCLK2          /* 将SPI4时钟源D2PCLK1重定义为D2PCLK2 */
#define  RCC_SPI5CLKSOURCE_D2PCLK1       RCC_SPI5CLKSOURCE_D2PCLK2          /* 将SPI5时钟源D2PCLK1重定义为D2PCLK2 */
#define  RCC_SPI45CLKSOURCE_D2PCLK1      RCC_SPI45CLKSOURCE_D2PCLK2         /* 将SPI45时钟源D2PCLK1重定义为D2PCLK2 */
#define  RCC_SPI45CLKSOURCE_CDPCLK1      RCC_SPI45CLKSOURCE_CDPCLK2         /* 将SPI45时钟源CDPCLK1重定义为CDPCLK2 */
#define  RCC_SPI45CLKSOURCE_PCLK1        RCC_SPI45CLKSOURCE_PCLK2           /* 将SPI45时钟源PCLK1重定义为PCLK2 */
#endif  /* 结束STM32H7条件编译 */

#define __WWDG_CLK_DISABLE __HAL_RCC_WWDG_CLK_DISABLE  /* 禁用WWDG时钟的简写宏 */
#define __WWDG_CLK_ENABLE __HAL_RCC_WWDG_CLK_ENABLE    /* 使能WWDG时钟的简写宏 */
#define __WWDG_CLK_SLEEP_DISABLE __HAL_RCC_WWDG_CLK_SLEEP_DISABLE  /* 在睡眠模式下禁用WWDG时钟的简写宏 */
#define __WWDG_CLK_SLEEP_ENABLE __HAL_RCC_WWDG_CLK_SLEEP_ENABLE    /* 在睡眠模式下使能WWDG时钟的简写宏 */
#define __WWDG_FORCE_RESET __HAL_RCC_WWDG_FORCE_RESET              /* 强制复位WWDG的简写宏 */
#define __WWDG_RELEASE_RESET __HAL_RCC_WWDG_RELEASE_RESET          /* 释放WWDG复位的简写宏 */

#define __TIM21_CLK_ENABLE   __HAL_RCC_TIM21_CLK_ENABLE            /* 使能TIM21时钟 */
#define __TIM21_CLK_DISABLE   __HAL_RCC_TIM21_CLK_DISABLE          /* 禁用TIM21时钟 */
#define __TIM21_FORCE_RESET   __HAL_RCC_TIM21_FORCE_RESET          /* 强制复位TIM21 */
#define __TIM21_RELEASE_RESET  __HAL_RCC_TIM21_RELEASE_RESET       /* 释放TIM21复位 */
#define __TIM21_CLK_SLEEP_ENABLE   __HAL_RCC_TIM21_CLK_SLEEP_ENABLE   /* 在睡眠模式下使能TIM21时钟 */
#define __TIM21_CLK_SLEEP_DISABLE   __HAL_RCC_TIM21_CLK_SLEEP_DISABLE /* 在睡眠模式下禁用TIM21时钟 */
#define __TIM22_CLK_ENABLE   __HAL_RCC_TIM22_CLK_ENABLE            /* 使能TIM22时钟 */
#define __TIM22_CLK_DISABLE   __HAL_RCC_TIM22_CLK_DISABLE          /* 禁用TIM22时钟 */
#define __TIM22_FORCE_RESET   __HAL_RCC_TIM22_FORCE_RESET          /* 强制复位TIM22 */
#define __TIM22_RELEASE_RESET  __HAL_RCC_TIM22_RELEASE_RESET       /* 释放TIM22复位 */
#define __TIM22_CLK_SLEEP_ENABLE   __HAL_RCC_TIM22_CLK_SLEEP_ENABLE   /* 在睡眠模式下使能TIM22时钟 */
#define __TIM22_CLK_SLEEP_DISABLE   __HAL_RCC_TIM22_CLK_SLEEP_DISABLE /* 在睡眠模式下禁用TIM22时钟 */
#define __CRS_CLK_DISABLE __HAL_RCC_CRS_CLK_DISABLE                /* 禁用CRS时钟 */
#define __CRS_CLK_ENABLE __HAL_RCC_CRS_CLK_ENABLE                  /* 使能CRS时钟 */
#define __CRS_CLK_SLEEP_DISABLE __HAL_RCC_CRS_CLK_SLEEP_DISABLE    /* 在睡眠模式下禁用CRS时钟 */
#define __CRS_CLK_SLEEP_ENABLE __HAL_RCC_CRS_CLK_SLEEP_ENABLE      /* 在睡眠模式下使能CRS时钟 */
#define __CRS_FORCE_RESET __HAL_RCC_CRS_FORCE_RESET                /* 强制复位CRS */
#define __CRS_RELEASE_RESET __HAL_RCC_CRS_RELEASE_RESET            /* 释放CRS复位 */
#define __RCC_BACKUPRESET_FORCE __HAL_RCC_BACKUPRESET_FORCE        /* 强制备份域复位 */
#define __RCC_BACKUPRESET_RELEASE __HAL_RCC_BACKUPRESET_RELEASE    /* 释放备份域复位 */