#define __ADC1_IS_CLK_ENABLED       __HAL_RCC_ADC1_IS_CLK_ENABLED  /* 宏定义：检查ADC1外设时钟是否使能 */
#define __ADC1_IS_CLK_DISABLED      __HAL_RCC_ADC1_IS_CLK_DISABLED /* 宏定义：检查ADC1外设时钟是否禁用 */
#define __ADC12_IS_CLK_ENABLED      __HAL_RCC_ADC12_IS_CLK_ENABLED /* 宏定义：检查ADC1和ADC2外设时钟是否使能 */
#define __ADC12_IS_CLK_DISABLED     __HAL_RCC_ADC12_IS_CLK_DISABLED /* 宏定义：检查ADC1和ADC2外设时钟是否禁用 */
#define __ADC34_IS_CLK_ENABLED      __HAL_RCC_ADC34_IS_CLK_ENABLED /* 宏定义：检查ADC3和ADC4外设时钟是否使能 */
#define __ADC34_IS_CLK_DISABLED     __HAL_RCC_ADC34_IS_CLK_DISABLED /* 宏定义：检查ADC3和ADC4外设时钟是否禁用 */
#define __CEC_IS_CLK_ENABLED        __HAL_RCC_CEC_IS_CLK_ENABLED   /* 宏定义：检查CEC（消费电子控制）外设时钟是否使能 */
#define __CEC_IS_CLK_DISABLED       __HAL_RCC_CEC_IS_CLK_DISABLED  /* 宏定义：检查CEC（消费电子控制）外设时钟是否禁用 */
#define __CRC_IS_CLK_ENABLED        __HAL_RCC_CRC_IS_CLK_ENABLED   /* 宏定义：检查CRC（循环冗余校验）外设时钟是否使能 */
#define __CRC_IS_CLK_DISABLED       __HAL_RCC_CRC_IS_CLK_DISABLED  /* 宏定义：检查CRC（循环冗余校验）外设时钟是否禁用 */
#define __DAC1_IS_CLK_ENABLED       __HAL_RCC_DAC1_IS_CLK_ENABLED  /* 宏定义：检查DAC1（数模转换器1）外设时钟是否使能 */
#define __DAC1_IS_CLK_DISABLED      __HAL_RCC_DAC1_IS_CLK_DISABLED /* 宏定义：检查DAC1（数模转换器1）外设时钟是否禁用 */
#define __DAC2_IS_CLK_ENABLED       __HAL_RCC_DAC2_IS_CLK_ENABLED  /* 宏定义：检查DAC2（数模转换器2）外设时钟是否使能 */
#define __DAC2_IS_CLK_DISABLED      __HAL_RCC_DAC2_IS_CLK_DISABLED /* 宏定义：检查DAC2（数模转换器2）外设时钟是否禁用 */
#define __DMA1_IS_CLK_ENABLED       __HAL_RCC_DMA1_IS_CLK_ENABLED  /* 宏定义：检查DMA1（直接内存访问控制器1）外设时钟是否使能 */
#define __DMA1_IS_CLK_DISABLED      __HAL_RCC_DMA1_IS_CLK_DISABLED /* 宏定义：检查DMA1（直接内存访问控制器1）外设时钟是否禁用 */
#define __DMA2_IS_CLK_ENABLED       __HAL_RCC_DMA2_IS_CLK_ENABLED  /* 宏定义：检查DMA2（直接内存访问控制器2）外设时钟是否使能 */
#define __DMA2_IS_CLK_DISABLED      __HAL_RCC_DMA2_IS_CLK_DISABLED /* 宏定义：检查DMA2（直接内存访问控制器2）外设时钟是否禁用 */
#define __FLITF_IS_CLK_ENABLED      __HAL_RCC_FLITF_IS_CLK_ENABLED /* 宏定义：检查FLITF（Flash接口）时钟是否使能 */
#define __FLITF_IS_CLK_DISABLED     __HAL_RCC_FLITF_IS_CLK_DISABLED /* 宏定义：检查FLITF（Flash接口）时钟是否禁用 */
#define __FMC_IS_CLK_ENABLED        __HAL_RCC_FMC_IS_CLK_ENABLED   /* 宏定义：检查FMC（灵活内存控制器）时钟是否使能 */
#define __FMC_IS_CLK_DISABLED       __HAL_RCC_FMC_IS_CLK_DISABLED  /* 宏定义：检查FMC（灵活内存控制器）时钟是否禁用 */
#define __GPIOA_IS_CLK_ENABLED      __HAL_RCC_GPIOA_IS_CLK_ENABLED /* 宏定义：检查GPIOA端口时钟是否使能 */
#define __GPIOA_IS_CLK_DISABLED     __HAL_RCC_GPIOA_IS_CLK_DISABLED /* 宏定义：检查GPIOA端口时钟是否禁用 */
#define __GPIOB_IS_CLK_ENABLED      __HAL_RCC_GPIOB_IS_CLK_ENABLED /* 宏定义：检查GPIOB端口时钟是否使能 */
#define __GPIOB_IS_CLK_DISABLED     __HAL_RCC_GPIOB_IS_CLK_DISABLED /* 宏定义：检查GPIOB端口时钟是否禁用 */
#define __GPIOC_IS_CLK_ENABLED      __HAL_RCC_GPIOC_IS_CLK_ENABLED /* 宏定义：检查GPIOC端口时钟是否使能 */
#define __GPIOC_IS_CLK_DISABLED     __HAL_RCC_GPIOC_IS_CLK_DISABLED /* 宏定义：检查GPIOC端口时钟是否禁用 */
#define __GPIOD_IS_CLK_ENABLED      __HAL_RCC_GPIOD_IS_CLK_ENABLED /* 宏定义：检查GPIOD端口时钟是否使能 */
#define __GPIOD_IS_CLK_DISABLED     __HAL_RCC_GPIOD_IS_CLK_DISABLED /* 宏定义：检查GPIOD端口时钟是否禁用 */
#define __GPIOE_IS_CLK_ENABLED      __HAL_RCC_GPIOE_IS_CLK_ENABLED /* 宏定义：检查GPIOE端口时钟是否使能 */
#define __GPIOE_IS_CLK_DISABLED     __HAL_RCC_GPIOE_IS_CLK_DISABLED /* 宏定义：检查GPIOE端口时钟是否禁用 */
#define __GPIOF_IS_CLK_ENABLED      __HAL_RCC_GPIOF_IS_CLK_ENABLED /* 宏定义：检查GPIOF端口时钟是否使能 */
#define __GPIOF_IS_CLK_DISABLED     __HAL_RCC_GPIOF_IS_CLK_DISABLED /* 宏定义：检查GPIOF端口时钟是否禁用 */
#define __GPIOG_IS_CLK_ENABLED      __HAL_RCC_GPIOG_IS_CLK_ENABLED /* 宏定义：检查GPIOG端口时钟是否使能 */
#define __GPIOG_IS_CLK_DISABLED     __HAL_RCC_GPIOG_IS_CLK_DISABLED /* 宏定义：检查GPIOG端口时钟是否禁用 */
#define __GPIOH_IS_CLK_ENABLED      __HAL_RCC_GPIOH_IS_CLK_ENABLED /* 宏定义：检查GPIOH端口时钟是否使能 */
#define __GPIOH_IS_CLK_DISABLED     __HAL_RCC_GPIOH_IS_CLK_DISABLED /* 宏定义：检查GPIOH端口时钟是否禁用 */
#define __HRTIM1_IS_CLK_ENABLED     __HAL_RCC_HRTIM1_IS_CLK_ENABLED /* 宏定义：检查HRTIM1（高分辨率定时器1）外设时钟是否使能 */
#define __HRTIM1_IS_CLK_DISABLED    __HAL_RCC_HRTIM1_IS_CLK_DISABLED /* 宏定义：检查HRTIM1（高分辨率定时器1）外设时钟是否禁用 */
#define __I2C1_IS_CLK_ENABLED       __HAL_RCC_I2C1_IS_CLK_ENABLED  /* 宏定义：检查I2C1外设时钟是否使能 */
#define __I2C1_IS_CLK_DISABLED      __HAL_RCC_I2C1_IS_CLK_DISABLED /* 宏定义：检查I2C1外设时钟是否禁用 */
#define __I2C2_IS_CLK_ENABLED       __HAL_RCC_I2C2_IS_CLK_ENABLED  /* 宏定义：检查I2C2外设时钟是否使能 */
#define __I2C2_IS_CLK_DISABLED      __HAL_RCC_I2C2_IS_CLK_DISABLED /* 宏定义：检查I2C2外设时钟是否禁用 */
#define __I2C3_IS_CLK_ENABLED       __HAL_RCC_I2C3_IS_CLK_ENABLED  /* 宏定义：检查I2C3外设时钟是否使能 */
#define __I2C3_IS_CLK_DISABLED      __HAL_RCC_I2C3_IS_CLK_DISABLED /* 宏定义：检查I2C3外设时钟是否禁用 */
#define __PWR_IS_CLK_ENABLED        __HAL_RCC_PWR_IS_CLK_ENABLED   /* 宏定义：检查PWR（电源控制）外设时钟是否使能 */
#define __PWR_IS_CLK_DISABLED       __HAL_RCC_PWR_IS_CLK_DISABLED  /* 宏定义：检查PWR（电源控制）外设时钟是否禁用 */
#define __SYSCFG_IS_CLK_ENABLED     __HAL_RCC_SYSCFG_IS_CLK_ENABLED /* 宏定义：检查SYSCFG（系统配置）时钟是否使能 */
#define __SYSCFG_IS_CLK_DISABLED    __HAL_RCC_SYSCFG_IS_CLK_DISABLED /* 宏定义：检查SYSCFG（系统配置）时钟是否禁用 */
#define __SPI1_IS_CLK_ENABLED       __HAL_RCC_SPI1_IS_CLK_ENABLED  /* 宏定义：检查SPI1外设时钟是否使能 */
#define __SPI1_IS_CLK_DISABLED      __HAL_RCC_SPI1_IS_CLK_DISABLED /* 宏定义：检查SPI1外设时钟是否禁用 */
#define __SPI2_IS_CLK_ENABLED       __HAL_RCC_SPI2_IS_CLK_ENABLED  /* 宏定义：检查SPI2外设时钟是否使能 */
#define __SPI2_IS_CLK_DISABLED      __HAL_RCC_SPI2_IS_CLK_DISABLED /* 宏定义：检查SPI2外设时钟是否禁用 */
#define __SPI3_IS_CLK_ENABLED       __HAL_RCC_SPI3_IS_CLK_ENABLED  /* 宏定义：检查SPI3外设时钟是否使能 */
#define __SPI3_IS_CLK_DISABLED      __HAL_RCC_SPI3_IS_CLK_DISABLED /* 宏定义：检查SPI3外设时钟是否禁用 */
#define __SPI4_IS_CLK_ENABLED       __HAL_RCC_SPI4_IS_CLK_ENABLED  /* 宏定义：检查SPI4外设时钟是否使能 */
#define __SPI4_IS_CLK_DISABLED      __HAL_RCC_SPI4_IS_CLK_DISABLED /* 宏定义：检查SPI4外设时钟是否禁用 */
#define __SDADC1_IS_CLK_ENABLED     __HAL_RCC_SDADC1_IS_CLK_ENABLED /* 宏定义：检查SDADC1（Sigma-Delta ADC1）外设时钟是否使能 */
#define __SDADC1_IS_CLK_DISABLED    __HAL_RCC_SDADC1_IS_CLK_DISABLED /* 宏定义：检查SDADC1（Sigma-Delta ADC1）外设时钟是否禁用 */
#define __SDADC2_IS_CLK_ENABLED     __HAL_RCC_SDADC2_IS_CLK_ENABLED /* 宏定义：检查SDADC2（Sigma-Delta ADC2）外设时钟是否使能 */
#define __SDADC2_IS_CLK_DISABLED    __HAL_RCC_SDADC2_IS_CLK_DISABLED /* 宏定义：检查SDADC2（Sigma-Delta ADC2）外设时钟是否禁用 */
#define __SDADC3_IS_CLK_ENABLED     __HAL_RCC_SDADC3_IS_CLK_ENABLED /* 宏定义：检查SDADC3（Sigma-Delta ADC3）外设时钟是否使能 */
#define __SDADC3_IS_CLK_DISABLED    __HAL_RCC_SDADC3_IS_CLK_DISABLED /* 宏定义：检查SDADC3（Sigma-Delta ADC3）外设时钟是否禁用 */
#define __SRAM_IS_CLK_ENABLED       __HAL_RCC_SRAM_IS_CLK_ENABLED  /* 宏定义：检查SRAM（静态随机存取存储器）时钟是否使能 */
#define __SRAM_IS_CLK_DISABLED      __HAL_RCC_SRAM_IS_CLK_DISABLED /* 宏定义：检查SRAM（静态随机存取存储器）时钟是否禁用 */
#define __TIM1_IS_CLK_ENABLED       __HAL_RCC_TIM1_IS_CLK_ENABLED  /* 宏定义：检查TIM1（高级控制定时器1）外设时钟是否使能 */
#define __TIM1_IS_CLK_DISABLED      __HAL_RCC_TIM1_IS_CLK_DISABLED /* 宏定义：检查TIM1（高级控制定时器1）外设时钟是否禁用 */
#define __TIM2_IS_CLK_ENABLED       __HAL_RCC_TIM2_IS_CLK_ENABLED  /* 宏定义：检查TIM2（通用定时器2）外设时钟是否使能 */
#define __TIM2_IS_CLK_DISABLED      __HAL_RCC_TIM2_IS_CLK_DISABLED /* 宏定义：检查TIM2（通用定时器2）外设时钟是否禁用 */
#define __TIM3_IS_CLK_ENABLED       __HAL_RCC_TIM3_IS_CLK_ENABLED  /* 宏定义：检查TIM3（通用定时器3）外设时钟是否使能 */
#define __TIM3_IS_CLK_DISABLED      __HAL_RCC_TIM3_IS_CLK_DISABLED /* 宏定义：检查TIM3（通用定时器3）外设时钟是否禁用 */
#define __TIM4_IS_CLK_ENABLED       __HAL_RCC_TIM4_IS_CLK_ENABLED  /* 宏定义：检查TIM4（通用定时器4）外设时钟是否使能 */
#define __TIM4_IS_CLK_DISABLED      __HAL_RCC_TIM4_IS_CLK_DISABLED /* 宏定义：检查TIM4（通用定时器4）外设时钟是否禁用 */
#define __TIM5_IS_CLK_ENABLED       __HAL_RCC_TIM5_IS_CLK_ENABLED  /* 宏定义：检查TIM5（通用定时器5）外设时钟是否使能 */
#define __TIM5_IS_CLK_DISABLED      __HAL_RCC_TIM5_IS_CLK_DISABLED /* 宏定义：检查TIM5（通用定时器5）外设时钟是否禁用 */
#define __TIM6_IS_CLK_ENABLED       __HAL_RCC_TIM6_IS_CLK_ENABLED  /* 宏定义：检查TIM6（基本定时器6）外设时钟是否使能 */
#define __TIM6_IS_CLK_DISABLED      __HAL_RCC_TIM6_IS_CLK_DISABLED /* 宏定义：检查TIM6（基本定时器6）外设时钟是否禁用 */
#define __TIM7_IS_CLK_ENABLED       __HAL_RCC_TIM7_IS_CLK_ENABLED  /* 宏定义：检查TIM7（基本定时器7）外设时钟是否使能 */
#define __TIM7_IS_CLK_DISABLED      __HAL_RCC_TIM7_IS_CLK_DISABLED /* 宏定义：检查TIM7（基本定时器7）外设时钟是否禁用 */
#define __TIM8_IS_CLK_ENABLED       __HAL_RCC_TIM8_IS_CLK_ENABLED  /* 宏定义：检查TIM8（高级控制定时器8）外设时钟是否使能 */
#define __TIM8_IS_CLK_DISABLED      __HAL_RCC_TIM8_IS_CLK_DISABLED /* 宏定义：检查TIM8（高级控制定时器8）外设时钟是否禁用 */
#define __TIM12_IS_CLK_ENABLED      __HAL_RCC_TIM12_IS_CLK_ENABLED /* 宏定义：检查TIM12（通用定时器12）外设时钟是否使能 */
#define __TIM12_IS_CLK_DISABLED     __HAL_RCC_TIM12_IS_CLK_DISABLED /* 宏定义：检查TIM12（通用定时器12）外设时钟是否禁用 */
#define __TIM13_IS_CLK_ENABLED      __HAL_RCC_TIM13_IS_CLK_ENABLED /* 宏定义：检查TIM13（通用定时器13）外设时钟是否使能 */
#define __TIM13_IS_CLK_DISABLED     __HAL_RCC_TIM13_IS_CLK_DISABLED /* 宏定义：检查TIM13（通用定时器13）外设时钟是否禁用 */
#define __TIM14_IS_CLK_ENABLED      __HAL_RCC_TIM14_IS_CLK_ENABLED /* 宏定义：检查TIM14（通用定时器14）外设时钟是否使能 */
#define __TIM14_IS_CLK_DISABLED     __HAL_RCC_TIM14_IS_CLK_DISABLED /* 宏定义：检查TIM14（通用定时器14）外设时钟是否禁用 */
#define __TIM15_IS_CLK_ENABLED      __HAL_RCC_TIM15_IS_CLK_ENABLED /* 宏定义：检查TIM15（通用定时器15）外设时钟是否使能 */
#define __TIM15_IS_CLK_DISABLED     __HAL_RCC_TIM15_IS_CLK_DISABLED /* 宏定义：检查TIM15（通用定时器15）外设时钟是否禁用 */
#define __TIM16_IS_CLK_ENABLED      __HAL_RCC_TIM16_IS_CLK_ENABLED /* 宏定义：检查TIM16（通用定时器16）外设时钟是否使能 */
#define __TIM16_IS_CLK_DISABLED     __HAL_RCC_TIM16_IS_CLK_DISABLED /* 宏定义：检查TIM16（通用定时器16）外设时钟是否禁用 */
#define __TIM17_IS_CLK_ENABLED      __HAL_RCC_TIM17_IS_CLK_ENABLED /* 宏定义：检查TIM17（通用定时器17）外设时钟是否使能 */
#define __TIM17_IS_CLK_DISABLED     __HAL_RCC_TIM17_IS_CLK_DISABLED /* 宏定义：检查TIM17（通用定时器17）外设时钟是否禁用 */
#define __TIM18_IS_CLK_ENABLED      __HAL_RCC_TIM18_IS_CLK_ENABLED /* 宏定义：检查TIM18（通用定时器18）外设时钟是否使能 */
#define __TIM18_IS_CLK_DISABLED     __HAL_RCC_TIM18_IS_CLK_DISABLED /* 宏定义：检查TIM18（通用定时器18）外设时钟是否禁用 */
#define __TIM19_IS_CLK_ENABLED      __HAL_RCC_TIM19_IS_CLK_ENABLED /* 宏定义：检查TIM19（通用定时器19）外设时钟是否使能 */
#define __TIM19_IS_CLK_DISABLED     __HAL_RCC_TIM19_IS_CLK_DISABLED /* 宏定义：检查TIM19（通用定时器19）外设时钟是否禁用 */
#define __TIM20_IS_CLK_ENABLED      __HAL_RCC_TIM20_IS_CLK_ENABLED /* 宏定义：检查TIM20（高级控制定时器20）外设时钟是否使能 */
#define __TIM20_IS_CLK_DISABLED     __HAL_RCC_TIM20_IS_CLK_DISABLED /* 宏定义：检查TIM20（高级控制定时器20）外设时钟是否禁用 */
#define __TSC_IS_CLK_ENABLED        __HAL_RCC_TSC_IS_CLK_ENABLED   /* 宏定义：检查TSC（触摸感应控制器）外设时钟是否使能 */
#define __TSC_IS_CLK_DISABLED       __HAL_RCC_TSC_IS_CLK_DISABLED  /* 宏定义：检查TSC（触摸感应控制器）外设时钟是否禁用 */
#define __UART4_IS_CLK_ENABLED      __HAL_RCC_UART4_IS_CLK_ENABLED /* 宏定义：检查UART4外设时钟是否使能 */
#define __UART4_IS_CLK_DISABLED     __HAL_RCC_UART4_IS_CLK_DISABLED /* 宏定义：检查UART4外设时钟是否禁用 */
#define __UART5_IS_CLK_ENABLED      __HAL_RCC_UART5_IS_CLK_ENABLED /* 宏定义：检查UART5外设时钟是否使能 */
#define __UART5_IS_CLK_DISABLED     __HAL_RCC_UART5_IS_CLK_DISABLED /* 宏定义：检查UART5外设时钟是否禁用 */
#define __USART1_IS_CLK_ENABLED     __HAL_RCC_USART1_IS_CLK_ENABLED /* 宏定义：检查USART1外设时钟是否使能 */
#define __USART1_IS_CLK_DISABLED    __HAL_RCC_USART1_IS_CLK_DISABLED /* 宏定义：检查USART1外设时钟是否禁用 */
#define __USART2_IS_CLK_ENABLED     __HAL_RCC_USART2_IS_CLK_ENABLED /* 宏定义：检查USART2外设时钟是否使能 */
#define __USART2_IS_CLK_DISABLED    __HAL_RCC_USART2_IS_CLK_DISABLED /* 宏定义：检查USART2外设时钟是否禁用 */
#define __USART3_IS_CLK_ENABLED     __HAL_RCC_USART3_IS_CLK_ENABLED /* 宏定义：检查USART3外设时钟是否使能 */
#define __USART3_IS_CLK_DISABLED    __HAL_RCC_USART3_IS_CLK_DISABLED /* 宏定义：检查USART3外设时钟是否禁用 */
#define __USB_IS_CLK_ENABLED        __HAL_RCC_USB_IS_CLK_ENABLED   /* 宏定义：检查USB外设时钟是否使能 */
#define __USB_IS_CLK_DISABLED       __HAL_RCC_USB_IS_CLK_DISABLED  /* 宏定义：检查USB外设时钟是否禁用 */
#define __WWDG_IS_CLK_ENABLED       __HAL_RCC_WWDG_IS_CLK_ENABLED  /* 宏定义：检查WWDG（窗口看门狗）外设时钟是否使能 */
#define __WWDG_IS_CLK_DISABLED      __HAL_RCC_WWDG_IS_CLK_DISABLED /* 宏定义：检查WWDG（窗口看门狗）外设时钟是否禁用 */

#if defined(STM32L1) /* 条件编译：如果定义了STM32L1系列微控制器 */
#define __HAL_RCC_CRYP_CLK_DISABLE         __HAL_RCC_AES_CLK_DISABLE        /* 宏定义：将CRYP（加密）时钟禁用映射到AES时钟禁用（L1系列中两者可能相同） */
#define __HAL_RCC_CRYP_CLK_ENABLE          __HAL_RCC_AES_CLK_ENABLE         /* 宏定义：将CRYP（加密）时钟使能映射到AES时钟使能 */
#define __HAL_RCC_CRYP_CLK_SLEEP_DISABLE   __HAL_RCC_AES_CLK_SLEEP_DISABLE  /* 宏定义：将CRYP（加密）睡眠时钟禁用映射到AES睡眠时钟禁用 */
#define __HAL_RCC_CRYP_CLK_SLEEP_ENABLE    __HAL_RCC_AES_CLK_SLEEP_ENABLE   /* 宏定义：将CRYP（加密）睡眠时钟使能映射到AES睡眠时钟使能 */
#define __HAL_RCC_CRYP_FORCE_RESET         __HAL_RCC_AES_FORCE_RESET        /* 宏定义：将CRYP（加密）强制复位映射到AES强制复位 */
#define __HAL_RCC_CRYP_RELEASE_RESET       __HAL_RCC_AES_RELEASE_RESET      /* 宏定义：将CRYP（加密）释放复位映射到AES释放复位 */
#endif /* STM32L1 */ /* 条件编译结束 */

#if defined(STM32F4) /* 条件编译：如果定义了STM32F4系列微控制器 */
#define __HAL_RCC_SDMMC1_FORCE_RESET       __HAL_RCC_SDIO_FORCE_RESET       /* 宏定义：将SDMMC1（SD卡/MMC接口1）强制复位映射到SDIO强制复位（F4系列中两者可能相同） */
#define __HAL_RCC_SDMMC1_RELEASE_RESET     __HAL_RCC_SDIO_RELEASE_RESET     /* 宏定义：将SDMMC1释放复位映射到SDIO释放复位 */
#define __HAL_RCC_SDMMC1_CLK_SLEEP_ENABLE  __HAL_RCC_SDIO_CLK_SLEEP_ENABLE  /* 宏定义：将SDMMC1睡眠时钟使能映射到SDIO睡眠时钟使能 */
#define __HAL_RCC_SDMMC1_CLK_SLEEP_DISABLE __HAL_RCC_SDIO_CLK_SLEEP_DISABLE /* 宏定义：将SDMMC1睡眠时钟禁用映射到SDIO睡眠时钟禁用 */
#define __HAL_RCC_SDMMC1_CLK_ENABLE        __HAL_RCC_SDIO_CLK_ENABLE        /* 宏定义：将SDMMC1时钟使能映射到SDIO时钟使能 */
#define __HAL_RCC_SDMMC1_CLK_DISABLE       __HAL_RCC_SDIO_CLK_DISABLE       /* 宏定义：将SDMMC1时钟禁用映射到SDIO时钟禁用 */
#define __HAL_RCC_SDMMC1_IS_CLK_ENABLED    __HAL_RCC_SDIO_IS_CLK_ENABLED    /* 宏定义：将检查SDMMC1时钟使能映射到检查SDIO时钟使能 */
#define __HAL_RCC_SDMMC1_IS_CLK_DISABLED   __HAL_RCC_SDIO_IS_CLK_DISABLED   /* 宏定义：将检查SDMMC1时钟禁用映射到检查SDIO时钟禁用 */
#define Sdmmc1ClockSelection               SdioClockSelection               /* 宏定义：将SDMMC1时钟选择类型重命名为SDIO时钟选择类型 */
#define RCC_PERIPHCLK_SDMMC1               RCC_PERIPHCLK_SDIO               /* 宏定义：将SDMMC1外设时钟标识映射到SDIO外设时钟标识 */
#define RCC_SDMMC1CLKSOURCE_CLK48          RCC_SDIOCLKSOURCE_CK48           /* 宏定义：将SDMMC1时钟源CLK48映射到SDIO时钟源CK48 */
#define RCC_SDMMC1CLKSOURCE_SYSCLK         RCC_SDIOCLKSOURCE_SYSCLK         /* 宏定义：将SDMMC1时钟源SYSCLK映射到SDIO时钟源SYSCLK */
#define __HAL_RCC_SDMMC1_CONFIG            __HAL_RCC_SDIO_CONFIG            /* 宏定义：将SDMMC1配置宏映射到SDIO配置宏 */
#define __HAL_RCC_GET_SDMMC1_SOURCE        __HAL_RCC_GET_SDIO_SOURCE        /* 宏定义：将获取SDMMC1时钟源宏映射到获取SDIO时钟源宏 */
#endif /* 条件编译结束，这里缺少对应的 `#endif`，但根据要求不补充 */