#define __RNG_CLK_DISABLE __HAL_RCC_RNG_CLK_DISABLE             // 禁用随机数生成器(RNG)时钟
#define __RNG_CLK_ENABLE __HAL_RCC_RNG_CLK_ENABLE               // 使能随机数生成器(RNG)时钟
#define __RNG_CLK_SLEEP_DISABLE __HAL_RCC_RNG_CLK_SLEEP_DISABLE // 在睡眠模式下禁用RNG时钟
#define __RNG_CLK_SLEEP_ENABLE __HAL_RCC_RNG_CLK_SLEEP_ENABLE   // 在睡眠模式下使能RNG时钟
#define __RNG_FORCE_RESET __HAL_RCC_RNG_FORCE_RESET             // 强制复位RNG外设
#define __RNG_RELEASE_RESET __HAL_RCC_RNG_RELEASE_RESET         // 释放RNG外设的复位

#define __SAI1_CLK_DISABLE __HAL_RCC_SAI1_CLK_DISABLE           // 禁用串行音频接口1(SAI1)时钟
#define __SAI1_CLK_ENABLE __HAL_RCC_SAI1_CLK_ENABLE             // 使能串行音频接口1(SAI1)时钟
#define __SAI1_CLK_SLEEP_DISABLE __HAL_RCC_SAI1_CLK_SLEEP_DISABLE // 在睡眠模式下禁用SAI1时钟
#define __SAI1_CLK_SLEEP_ENABLE __HAL_RCC_SAI1_CLK_SLEEP_ENABLE // 在睡眠模式下使能SAI1时钟
#define __SAI1_FORCE_RESET __HAL_RCC_SAI1_FORCE_RESET           // 强制复位SAI1外设
#define __SAI1_RELEASE_RESET __HAL_RCC_SAI1_RELEASE_RESET       // 释放SAI1外设的复位

#define __SAI2_CLK_DISABLE __HAL_RCC_SAI2_CLK_DISABLE           // 禁用串行音频接口2(SAI2)时钟
#define __SAI2_CLK_ENABLE __HAL_RCC_SAI2_CLK_ENABLE             // 使能串行音频接口2(SAI2)时钟
#define __SAI2_CLK_SLEEP_DISABLE __HAL_RCC_SAI2_CLK_SLEEP_DISABLE // 在睡眠模式下禁用SAI2时钟
#define __SAI2_CLK_SLEEP_ENABLE __HAL_RCC_SAI2_CLK_SLEEP_ENABLE // 在睡眠模式下使能SAI2时钟
#define __SAI2_FORCE_RESET __HAL_RCC_SAI2_FORCE_RESET           // 强制复位SAI2外设
#define __SAI2_RELEASE_RESET __HAL_RCC_SAI2_RELEASE_RESET       // 释放SAI2外设的复位

#define __SDIO_CLK_DISABLE __HAL_RCC_SDIO_CLK_DISABLE           // 禁用安全数字输入输出(SDIO)时钟
#define __SDIO_CLK_ENABLE __HAL_RCC_SDIO_CLK_ENABLE             // 使能安全数字输入输出(SDIO)时钟

#define __SDMMC_CLK_DISABLE __HAL_RCC_SDMMC_CLK_DISABLE         // 禁用安全数字多媒体卡(SDMMC)时钟
#define __SDMMC_CLK_ENABLE __HAL_RCC_SDMMC_CLK_ENABLE           // 使能安全数字多媒体卡(SDMMC)时钟
#define __SDMMC_CLK_SLEEP_DISABLE __HAL_RCC_SDMMC_CLK_SLEEP_DISABLE // 在睡眠模式下禁用SDMMC时钟
#define __SDMMC_CLK_SLEEP_ENABLE __HAL_RCC_SDMMC_CLK_SLEEP_ENABLE // 在睡眠模式下使能SDMMC时钟
#define __SDMMC_FORCE_RESET __HAL_RCC_SDMMC_FORCE_RESET         // 强制复位SDMMC外设
#define __SDMMC_RELEASE_RESET __HAL_RCC_SDMMC_RELEASE_RESET     // 释放SDMMC外设的复位

#define __SPI1_CLK_DISABLE __HAL_RCC_SPI1_CLK_DISABLE           // 禁用串行外设接口1(SPI1)时钟
#define __SPI1_CLK_ENABLE __HAL_RCC_SPI1_CLK_ENABLE             // 使能串行外设接口1(SPI1)时钟
#define __SPI1_CLK_SLEEP_DISABLE __HAL_RCC_SPI1_CLK_SLEEP_DISABLE // 在睡眠模式下禁用SPI1时钟
#define __SPI1_CLK_SLEEP_ENABLE __HAL_RCC_SPI1_CLK_SLEEP_ENABLE // 在睡眠模式下使能SPI1时钟
#define __SPI1_FORCE_RESET __HAL_RCC_SPI1_FORCE_RESET           // 强制复位SPI1外设
#define __SPI1_RELEASE_RESET __HAL_RCC_SPI1_RELEASE_RESET       // 释放SPI1外设的复位

#define __SPI2_CLK_DISABLE __HAL_RCC_SPI2_CLK_DISABLE           // 禁用串行外设接口2(SPI2)时钟
#define __SPI2_CLK_ENABLE __HAL_RCC_SPI2_CLK_ENABLE             // 使能串行外设接口2(SPI2)时钟
#define __SPI2_CLK_SLEEP_DISABLE __HAL_RCC_SPI2_CLK_SLEEP_DISABLE // 在睡眠模式下禁用SPI2时钟
#define __SPI2_CLK_SLEEP_ENABLE __HAL_RCC_SPI2_CLK_SLEEP_ENABLE // 在睡眠模式下使能SPI2时钟
#define __SPI2_FORCE_RESET __HAL_RCC_SPI2_FORCE_RESET           // 强制复位SPI2外设
#define __SPI2_RELEASE_RESET __HAL_RCC_SPI2_RELEASE_RESET       // 释放SPI2外设的复位

#define __SPI3_CLK_DISABLE __HAL_RCC_SPI3_CLK_DISABLE           // 禁用串行外设接口3(SPI3)时钟
#define __SPI3_CLK_ENABLE __HAL_RCC_SPI3_CLK_ENABLE             // 使能串行外设接口3(SPI3)时钟
#define __SPI3_CLK_SLEEP_DISABLE __HAL_RCC_SPI3_CLK_SLEEP_DISABLE // 在睡眠模式下禁用SPI3时钟
#define __SPI3_CLK_SLEEP_ENABLE __HAL_RCC_SPI3_CLK_SLEEP_ENABLE // 在睡眠模式下使能SPI3时钟
#define __SPI3_FORCE_RESET __HAL_RCC_SPI3_FORCE_RESET           // 强制复位SPI3外设
#define __SPI3_RELEASE_RESET __HAL_RCC_SPI3_RELEASE_RESET       // 释放SPI3外设的复位

#define __SRAM_CLK_DISABLE __HAL_RCC_SRAM_CLK_DISABLE           // 禁用SRAM时钟
#define __SRAM_CLK_ENABLE __HAL_RCC_SRAM_CLK_ENABLE             // 使能SRAM时钟
#define __SRAM1_CLK_SLEEP_DISABLE __HAL_RCC_SRAM1_CLK_SLEEP_DISABLE // 在睡眠模式下禁用SRAM1时钟
#define __SRAM1_CLK_SLEEP_ENABLE __HAL_RCC_SRAM1_CLK_SLEEP_ENABLE // 在睡眠模式下使能SRAM1时钟
#define __SRAM2_CLK_SLEEP_DISABLE __HAL_RCC_SRAM2_CLK_SLEEP_DISABLE // 在睡眠模式下禁用SRAM2时钟
#define __SRAM2_CLK_SLEEP_ENABLE __HAL_RCC_SRAM2_CLK_SLEEP_ENABLE // 在睡眠模式下使能SRAM2时钟

#define __SWPMI1_CLK_DISABLE __HAL_RCC_SWPMI1_CLK_DISABLE       // 禁用单线协议管理器接口1(SWPMI1)时钟
#define __SWPMI1_CLK_ENABLE __HAL_RCC_SWPMI1_CLK_ENABLE         // 使能单线协议管理器接口1(SWPMI1)时钟
#define __SWPMI1_CLK_SLEEP_DISABLE __HAL_RCC_SWPMI1_CLK_SLEEP_DISABLE // 在睡眠模式下禁用SWPMI1时钟
#define __SWPMI1_CLK_SLEEP_ENABLE __HAL_RCC_SWPMI1_CLK_SLEEP_ENABLE // 在睡眠模式下使能SWPMI1时钟
#define __SWPMI1_FORCE_RESET __HAL_RCC_SWPMI1_FORCE_RESET       // 强制复位SWPMI1外设
#define __SWPMI1_RELEASE_RESET __HAL_RCC_SWPMI1_RELEASE_RESET   // 释放SWPMI1外设的复位

#define __SYSCFG_CLK_DISABLE __HAL_RCC_SYSCFG_CLK_DISABLE       // 禁用系统配置(SYSCFG)时钟
#define __SYSCFG_CLK_ENABLE __HAL_RCC_SYSCFG_CLK_ENABLE         // 使能系统配置(SYSCFG)时钟
#define __SYSCFG_CLK_SLEEP_DISABLE __HAL_RCC_SYSCFG_CLK_SLEEP_DISABLE // 在睡眠模式下禁用SYSCFG时钟
#define __SYSCFG_CLK_SLEEP_ENABLE __HAL_RCC_SYSCFG_CLK_SLEEP_ENABLE // 在睡眠模式下使能SYSCFG时钟
#define __SYSCFG_FORCE_RESET __HAL_RCC_SYSCFG_FORCE_RESET       // 强制复位SYSCFG外设
#define __SYSCFG_RELEASE_RESET __HAL_RCC_SYSCFG_RELEASE_RESET   // 释放SYSCFG外设的复位

#define __TIM1_CLK_DISABLE __HAL_RCC_TIM1_CLK_DISABLE           // 禁用定时器1(TIM1)时钟
#define __TIM1_CLK_ENABLE __HAL_RCC_TIM1_CLK_ENABLE             // 使能定时器1(TIM1)时钟
#define __TIM1_CLK_SLEEP_DISABLE __HAL_RCC_TIM1_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM1时钟
#define __TIM1_CLK_SLEEP_ENABLE __HAL_RCC_TIM1_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM1时钟
#define __TIM1_FORCE_RESET __HAL_RCC_TIM1_FORCE_RESET           // 强制复位TIM1外设
#define __TIM1_RELEASE_RESET __HAL_RCC_TIM1_RELEASE_RESET       // 释放TIM1外设的复位

#define __TIM10_CLK_DISABLE __HAL_RCC_TIM10_CLK_DISABLE         // 禁用定时器10(TIM10)时钟
#define __TIM10_CLK_ENABLE __HAL_RCC_TIM10_CLK_ENABLE           // 使能定时器10(TIM10)时钟
#define __TIM10_FORCE_RESET __HAL_RCC_TIM10_FORCE_RESET         // 强制复位TIM10外设
#define __TIM10_RELEASE_RESET __HAL_RCC_TIM10_RELEASE_RESET     // 释放TIM10外设的复位

#define __TIM11_CLK_DISABLE __HAL_RCC_TIM11_CLK_DISABLE         // 禁用定时器11(TIM11)时钟
#define __TIM11_CLK_ENABLE __HAL_RCC_TIM11_CLK_ENABLE           // 使能定时器11(TIM11)时钟
#define __TIM11_FORCE_RESET __HAL_RCC_TIM11_FORCE_RESET         // 强制复位TIM11外设
#define __TIM11_RELEASE_RESET __HAL_RCC_TIM11_RELEASE_RESET     // 释放TIM11外设的复位

#define __TIM12_CLK_DISABLE __HAL_RCC_TIM12_CLK_DISABLE         // 禁用定时器12(TIM12)时钟
#define __TIM12_CLK_ENABLE __HAL_RCC_TIM12_CLK_ENABLE           // 使能定时器12(TIM12)时钟
#define __TIM12_FORCE_RESET __HAL_RCC_TIM12_FORCE_RESET         // 强制复位TIM12外设
#define __TIM12_RELEASE_RESET __HAL_RCC_TIM12_RELEASE_RESET     // 释放TIM12外设的复位

#define __TIM13_CLK_DISABLE __HAL_RCC_TIM13_CLK_DISABLE         // 禁用定时器13(TIM13)时钟
#define __TIM13_CLK_ENABLE __HAL_RCC_TIM13_CLK_ENABLE           // 使能定时器13(TIM13)时钟
#define __TIM13_FORCE_RESET __HAL_RCC_TIM13_FORCE_RESET         // 强制复位TIM13外设
#define __TIM13_RELEASE_RESET __HAL_RCC_TIM13_RELEASE_RESET     // 释放TIM13外设的复位

#define __TIM14_CLK_DISABLE __HAL_RCC_TIM14_CLK_DISABLE         // 禁用定时器14(TIM14)时钟
#define __TIM14_CLK_ENABLE __HAL_RCC_TIM14_CLK_ENABLE           // 使能定时器14(TIM14)时钟
#define __TIM14_FORCE_RESET __HAL_RCC_TIM14_FORCE_RESET         // 强制复位TIM14外设
#define __TIM14_RELEASE_RESET __HAL_RCC_TIM14_RELEASE_RESET     // 释放TIM14外设的复位

#define __TIM15_CLK_DISABLE __HAL_RCC_TIM15_CLK_DISABLE         // 禁用定时器15(TIM15)时钟
#define __TIM15_CLK_ENABLE __HAL_RCC_TIM15_CLK_ENABLE           // 使能定时器15(TIM15)时钟
#define __TIM15_CLK_SLEEP_DISABLE __HAL_RCC_TIM15_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM15时钟
#define __TIM15_CLK_SLEEP_ENABLE __HAL_RCC_TIM15_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM15时钟
#define __TIM15_FORCE_RESET __HAL_RCC_TIM15_FORCE_RESET         // 强制复位TIM15外设
#define __TIM15_RELEASE_RESET __HAL_RCC_TIM15_RELEASE_RESET     // 释放TIM15外设的复位

#define __TIM16_CLK_DISABLE __HAL_RCC_TIM16_CLK_DISABLE         // 禁用定时器16(TIM16)时钟
#define __TIM16_CLK_ENABLE __HAL_RCC_TIM16_CLK_ENABLE           // 使能定时器16(TIM16)时钟
#define __TIM16_CLK_SLEEP_DISABLE __HAL_RCC_TIM16_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM16时钟
#define __TIM16_CLK_SLEEP_ENABLE __HAL_RCC_TIM16_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM16时钟
#define __TIM16_FORCE_RESET __HAL_RCC_TIM16_FORCE_RESET         // 强制复位TIM16外设
#define __TIM16_RELEASE_RESET __HAL_RCC_TIM16_RELEASE_RESET     // 释放TIM16外设的复位

#define __TIM17_CLK_DISABLE __HAL_RCC_TIM17_CLK_DISABLE         // 禁用定时器17(TIM17)时钟
#define __TIM17_CLK_ENABLE __HAL_RCC_TIM17_CLK_ENABLE           // 使能定时器17(TIM17)时钟
#define __TIM17_CLK_SLEEP_DISABLE __HAL_RCC_TIM17_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM17时钟
#define __TIM17_CLK_SLEEP_ENABLE __HAL_RCC_TIM17_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM17时钟
#define __TIM17_FORCE_RESET __HAL_RCC_TIM17_FORCE_RESET         // 强制复位TIM17外设
#define __TIM17_RELEASE_RESET __HAL_RCC_TIM17_RELEASE_RESET     // 释放TIM17外设的复位

#define __TIM2_CLK_DISABLE __HAL_RCC_TIM2_CLK_DISABLE           // 禁用定时器2(TIM2)时钟
#define __TIM2_CLK_ENABLE __HAL_RCC_TIM2_CLK_ENABLE             // 使能定时器2(TIM2)时钟
#define __TIM2_CLK_SLEEP_DISABLE __HAL_RCC_TIM2_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM2时钟
#define __TIM2_CLK_SLEEP_ENABLE __HAL_RCC_TIM2_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM2时钟
#define __TIM2_FORCE_RESET __HAL_RCC_TIM2_FORCE_RESET           // 强制复位TIM2外设
#define __TIM2_RELEASE_RESET __HAL_RCC_TIM2_RELEASE_RESET       // 释放TIM2外设的复位

#define __TIM3_CLK_DISABLE __HAL_RCC_TIM3_CLK_DISABLE           // 禁用定时器3(TIM3)时钟
#define __TIM3_CLK_ENABLE __HAL_RCC_TIM3_CLK_ENABLE             // 使能定时器3(TIM3)时钟
#define __TIM3_CLK_SLEEP_DISABLE __HAL_RCC_TIM3_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM3时钟
#define __TIM3_CLK_SLEEP_ENABLE __HAL_RCC_TIM3_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM3时钟
#define __TIM3_FORCE_RESET __HAL_RCC_TIM3_FORCE_RESET           // 强制复位TIM3外设
#define __TIM3_RELEASE_RESET __HAL_RCC_TIM3_RELEASE_RESET       // 释放TIM3外设的复位

#define __TIM4_CLK_DISABLE __HAL_RCC_TIM4_CLK_DISABLE           // 禁用定时器4(TIM4)时钟
#define __TIM4_CLK_ENABLE __HAL_RCC_TIM4_CLK_ENABLE             // 使能定时器4(TIM4)时钟
#define __TIM4_CLK_SLEEP_DISABLE __HAL_RCC_TIM4_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM4时钟
#define __TIM4_CLK_SLEEP_ENABLE __HAL_RCC_TIM4_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM4时钟
#define __TIM4_FORCE_RESET __HAL_RCC_TIM4_FORCE_RESET           // 强制复位TIM4外设
#define __TIM4_RELEASE_RESET __HAL_RCC_TIM4_RELEASE_RESET       // 释放TIM4外设的复位

#define __TIM5_CLK_DISABLE __HAL_RCC_TIM5_CLK_DISABLE           // 禁用定时器5(TIM5)时钟
#define __TIM5_CLK_ENABLE __HAL_RCC_TIM5_CLK_ENABLE             // 使能定时器5(TIM5)时钟
#define __TIM5_CLK_SLEEP_DISABLE __HAL_RCC_TIM5_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM5时钟
#define __TIM5_CLK_SLEEP_ENABLE __HAL_RCC_TIM5_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM5时钟
#define __TIM5_FORCE_RESET __HAL_RCC_TIM5_FORCE_RESET           // 强制复位TIM5外设
#define __TIM5_RELEASE_RESET __HAL_RCC_TIM5_RELEASE_RESET       // 释放TIM5外设的复位

#define __TIM6_CLK_DISABLE __HAL_RCC_TIM6_CLK_DISABLE           // 禁用定时器6(TIM6)时钟
#define __TIM6_CLK_ENABLE __HAL_RCC_TIM6_CLK_ENABLE             // 使能定时器6(TIM6)时钟
#define __TIM6_CLK_SLEEP_DISABLE __HAL_RCC_TIM6_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM6时钟
#define __TIM6_CLK_SLEEP_ENABLE __HAL_RCC_TIM6_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM6时钟
#define __TIM6_FORCE_RESET __HAL_RCC_TIM6_FORCE_RESET           // 强制复位TIM6外设
#define __TIM6_RELEASE_RESET __HAL_RCC_TIM6_RELEASE_RESET       // 释放TIM6外设的复位

#define __TIM7_CLK_DISABLE __HAL_RCC_TIM7_CLK_DISABLE           // 禁用定时器7(TIM7)时钟
#define __TIM7_CLK_ENABLE __HAL_RCC_TIM7_CLK_ENABLE             // 使能定时器7(TIM7)时钟
#define __TIM7_CLK_SLEEP_DISABLE __HAL_RCC_TIM7_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM7时钟
#define __TIM7_CLK_SLEEP_ENABLE __HAL_RCC_TIM7_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM7时钟
#define __TIM7_FORCE_RESET __HAL_RCC_TIM7_FORCE_RESET           // 强制复位TIM7外设
#define __TIM7_RELEASE_RESET __HAL_RCC_TIM7_RELEASE_RESET       // 释放TIM7外设的复位

#define __TIM8_CLK_DISABLE __HAL_RCC_TIM8_CLK_DISABLE           // 禁用定时器8(TIM8)时钟
#define __TIM8_CLK_ENABLE __HAL_RCC_TIM8_CLK_ENABLE             // 使能定时器8(TIM8)时钟
#define __TIM8_CLK_SLEEP_DISABLE __HAL_RCC_TIM8_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TIM8时钟
#define __TIM8_CLK_SLEEP_ENABLE __HAL_RCC_TIM8_CLK_SLEEP_ENABLE // 在睡眠模式下使能TIM8时钟
#define __TIM8_FORCE_RESET __HAL_RCC_TIM8_FORCE_RESET           // 强制复位TIM8外设
#define __TIM8_RELEASE_RESET __HAL_RCC_TIM8_RELEASE_RESET       // 释放TIM8外设的复位

#define __TIM9_CLK_DISABLE __HAL_RCC_TIM9_CLK_DISABLE           // 禁用定时器9(TIM9)时钟
#define __TIM9_CLK_ENABLE __HAL_RCC_TIM9_CLK_ENABLE             // 使能定时器9(TIM9)时钟
#define __TIM9_FORCE_RESET __HAL_RCC_TIM9_FORCE_RESET           // 强制复位TIM9外设
#define __TIM9_RELEASE_RESET __HAL_RCC_TIM9_RELEASE_RESET       // 释放TIM9外设的复位

#define __TSC_CLK_DISABLE __HAL_RCC_TSC_CLK_DISABLE             // 禁用触摸感应控制器(TSC)时钟
#define __TSC_CLK_ENABLE __HAL_RCC_TSC_CLK_ENABLE               // 使能触摸感应控制器(TSC)时钟
#define __TSC_CLK_SLEEP_DISABLE __HAL_RCC_TSC_CLK_SLEEP_DISABLE // 在睡眠模式下禁用TSC时钟
#define __TSC_CLK_SLEEP_ENABLE __HAL_RCC_TSC_CLK_SLEEP_ENABLE   // 在睡眠模式下使能TSC时钟
#define __TSC_FORCE_RESET __HAL_RCC_TSC_FORCE_RESET             // 强制复位TSC外设
#define __TSC_RELEASE_RESET __HAL_RCC_TSC_RELEASE_RESET         // 释放TSC外设的复位

#define __UART4_CLK_DISABLE __HAL_RCC_UART4_CLK_DISABLE         // 禁用通用异步收发器4(UART4)时钟
#define __UART4_CLK_ENABLE __HAL_RCC_UART4_CLK_ENABLE           // 使能通用异步收发器4(UART4)时钟
#define __UART4_CLK_SLEEP_DISABLE __HAL_RCC_UART4_CLK_SLEEP_DISABLE // 在睡眠模式下禁用UART4时钟
#define __UART4_CLK_SLEEP_ENABLE __HAL_RCC_UART4_CLK_SLEEP_ENABLE // 在睡眠模式下使能UART4时钟
#define __UART4_FORCE_RESET __HAL_RCC_UART4_FORCE_RESET         // 强制复位UART4外设
#define __UART4_RELEASE_RESET __HAL_RCC_UART4_RELEASE_RESET     // 释放UART4外设的复位

#define __UART5_CLK_DISABLE __HAL_RCC_UART5_CLK_DISABLE         // 禁用通用异步收发器5(UART5)时钟
#define __UART5_CLK_ENABLE __HAL_RCC_UART5_CLK_ENABLE           // 使能通用异步收发器5(UART5)时钟
#define __UART5_CLK_SLEEP_DISABLE __HAL_RCC_UART5_CLK_SLEEP_DISABLE // 在睡眠模式下禁用UART5时钟
#define __UART5_CLK_SLEEP_ENABLE __HAL_RCC_UART5_CLK_SLEEP_ENABLE // 在睡眠模式下使能UART5时钟
#define __UART5_FORCE_RESET __HAL_RCC_UART5_FORCE_RESET         // 强制复位UART5外设
#define __UART5_RELEASE_RESET __HAL_RCC_UART5_RELEASE_RESET     // 释放UART5外设的复位

#define __USART1_CLK_DISABLE __HAL_RCC_USART1_CLK_DISABLE       // 禁用通用同步异步收发器1(USART1)时钟
#define __USART1_CLK_ENABLE __HAL_RCC_USART1_CLK_ENABLE         // 使能通用同步异步收发器1(USART1)时钟
#define __USART1_CLK_SLEEP_DISABLE __HAL_RCC_USART1_CLK_SLEEP_DISABLE // 在睡眠模式下禁用USART1时钟
#define __USART1_CLK_SLEEP_ENABLE __HAL_RCC_USART1_CLK_SLEEP_ENABLE // 在睡眠模式下使能USART1时钟
#define __USART1_FORCE_RESET __HAL_RCC_USART1_FORCE_RESET       // 强制复位USART1外设
#define __USART1_RELEASE_RESET __HAL_RCC_USART1_RELEASE_RESET   // 释放USART1外设的复位

#define __USART2_CLK_DISABLE __HAL_RCC_USART2_CLK_DISABLE       // 禁用通用同步异步收发器2(USART2)时钟
#define __USART2_CLK_ENABLE __HAL_RCC_USART2_CLK_ENABLE         // 使能通用同步异步收发器2(USART2)时钟
#define __USART2_CLK_SLEEP_DISABLE __HAL_RCC_USART2_CLK_SLEEP_DISABLE // 在睡眠模式下禁用USART2时钟
#define __USART2_CLK_SLEEP_ENABLE __HAL_RCC_USART2_CLK_SLEEP_ENABLE // 在睡眠模式下使能USART2时钟
#define __USART2_FORCE_RESET __HAL_RCC_USART2_FORCE_RESET       // 强制复位USART2外设
#define __USART2_RELEASE_RESET __HAL_RCC_USART2_RELEASE_RESET   // 释放USART2外设的复位

#define __USART3_CLK_DISABLE __HAL_RCC_USART3_CLK_DISABLE       // 禁用通用同步异步收发器3(USART3)时钟
#define __USART3_CLK_ENABLE __HAL_RCC_USART3_CLK_ENABLE         // 使能通用同步异步收发器3(USART3)时钟
#define __USART3_CLK_SLEEP_DISABLE __HAL_RCC_USART3_CLK_SLEEP_DISABLE // 在睡眠模式下禁用USART3时钟
#define __USART3_CLK_SLEEP_ENABLE __HAL_RCC_USART3_CLK_SLEEP_ENABLE // 在睡眠模式下使能USART3时钟
#define __USART3_FORCE_RESET __HAL_RCC_USART3_FORCE_RESET       // 强制复位USART3外设
#define __USART3_RELEASE_RESET __HAL_RCC_USART3_RELEASE_RESET   // 释放USART3外设的复位

// USART4宏定义指向UART4的宏，USART4与UART4在某些芯片上功能相同
#define __USART4_CLK_DISABLE        __HAL_RCC_UART4_CLK_DISABLE        // 禁用USART4时钟（实际使用UART4的时钟控制）
#define __USART4_CLK_ENABLE         __HAL_RCC_UART4_CLK_ENABLE         // 使能USART4时钟（实际使用UART4的时钟控制）
#define __USART4_CLK_SLEEP_ENABLE   __HAL_RCC_UART4_CLK_SLEEP_ENABLE   // 在睡眠模式下使能USART4时钟（实际使用UART4的时钟控制）
#define __USART4_CLK_SLEEP_DISABLE  __HAL_RCC_UART4_CLK_SLEEP_DISABLE  // 在睡眠模式下禁用USART4时钟（实际使用UART4的时钟控制）
#define __USART4_FORCE_RESET        __HAL_RCC_UART4_FORCE_RESET        // 强制复位USART4外设（实际使用UART4的复位控制）
#define __USART4_RELEASE_RESET      __HAL_RCC_UART4_RELEASE_RESET      // 释放USART4外设的复位（实际使用UART4的复位控制）

// USART5宏定义指向UART5的宏，USART5与UART5在某些芯片上功能相同
#define __USART5_CLK_DISABLE        __HAL_RCC_UART5_CLK_DISABLE        // 禁用USART5时钟（实际使用UART5的时钟控制）
#define __USART5_CLK_ENABLE         __HAL_RCC_UART5_CLK_ENABLE         // 使能USART5时钟（实际使用UART5的时钟控制）
#define __USART5_CLK_SLEEP_ENABLE   __HAL_RCC_UART5_CLK_SLEEP_ENABLE   // 在睡眠模式下使能USART5时钟（实际使用UART5的时钟控制）
#define __USART5_CLK_SLEEP_DISABLE  __HAL_RCC_UART5_CLK_SLEEP_DISABLE  // 在睡眠模式下禁用USART5时钟（实际使用UART5的时钟控制）
#define __USART5_FORCE_RESET        __HAL_RCC_UART5_FORCE_RESET        // 强制复位USART5外设（实际使用UART5的复位控制）
#define __USART5_RELEASE_RESET      __HAL_RCC_UART5_RELEASE_RESET      // 释放USART5外设的复位（实际使用UART5的复位控制）

#define __USART7_CLK_DISABLE        __HAL_RCC_UART7_CLK_DISABLE        // 禁用USART7时钟
#define __USART7_CLK_ENABLE         __HAL_RCC_UART7_CLK_ENABLE         // 使能USART7时钟
#define __USART7_FORCE_RESET        __HAL_RCC_UART7_FORCE_RESET        // 强制复位USART7外设
#define __USART7_RELEASE_RESET      __HAL_RCC_UART7_RELEASE_RESET      // 释放USART7外设的复位

#define __USART8_CLK_DISABLE        __HAL_RCC_UART8_CLK_DISABLE        // 禁用USART8时钟
#define __USART8_CLK_ENABLE         __HAL_RCC_UART8_CLK_ENABLE         // 使能USART8时钟
#define __USART8_FORCE_RESET        __HAL_RCC_UART8_FORCE_RESET        // 强制复位USART8外设
#define __USART8_RELEASE_RESET      __HAL_RCC_UART8_RELEASE_RESET      // 释放USART8外设的复位

#define __USB_CLK_DISABLE         __HAL_RCC_USB_CLK_DISABLE            // 禁用USB时钟
#define __USB_CLK_ENABLE          __HAL_RCC_USB_CLK_ENABLE             // 使能USB时钟
#define __USB_FORCE_RESET         __HAL_RCC_USB_FORCE_RESET            // 强制复位USB外设
#define __USB_CLK_SLEEP_ENABLE    __HAL_RCC_USB_CLK_SLEEP_ENABLE       // 在睡眠模式下使能USB时钟
#define __USB_CLK_SLEEP_DISABLE   __HAL_RCC_USB_CLK_SLEEP_DISABLE      // 在睡眠模式下禁用USB时钟
#define __USB_OTG_FS_CLK_DISABLE __HAL_RCC_USB_OTG_FS_CLK_DISABLE      // 禁用USB OTG FS时钟
#define __USB_OTG_FS_CLK_ENABLE __HAL_RCC_USB_OTG_FS_CLK_ENABLE        // 使能USB OTG FS时钟
#define __USB_RELEASE_RESET __HAL_RCC_USB_RELEASE_RESET                // 释放USB外设的复位