/*
  以下是外设时钟控制相关的宏定义别名。
  为了保持代码兼容性或简化书写，旧版的宏名称被映射到新版HAL库宏名称。
  主要涉及：RNG(随机数生成器), SAI(音频接口), SDIO/SDMMC(存储卡接口),
  SPI(串行外设接口), SRAM(静态内存), SWPMI(单线协议接口),
  SYSCFG(系统配置), TIM(定时器), TSC(触摸传感),
  UART/USART(串口), USB(通用串行总线), WWDG(窗口看门狗)等。
  操作类型包括：时钟使能(CLK_ENABLE)、时钟关闭(CLK_DISABLE)、
 睡眠模式时钟使能(CLK_SLEEP_ENABLE)、睡眠模式时钟关闭(CLK_SLEEP_DISABLE)、
	强制复位(FORCE_RESET)、释放复位(RELEASE_RESET)。
*/

/* RNG 随机数生成器 时钟控制 */
#define __RNG_CLK_DISABLE __HAL_RCC_RNG_CLK_DISABLE // 关闭 RNG 时钟
#define __RNG_CLK_ENABLE __HAL_RCC_RNG_CLK_ENABLE // 使能 RNG 时钟
#define __RNG_CLK_SLEEP_DISABLE __HAL_RCC_RNG_CLK_SLEEP_DISABLE // 睡眠模式下关闭 RNG 时钟
#define __RNG_CLK_SLEEP_ENABLE __HAL_RCC_RNG_CLK_SLEEP_ENABLE // 睡眠模式下使能 RNG 时钟
#define __RNG_FORCE_RESET __HAL_RCC_RNG_FORCE_RESET // 强制复位 RNG
#define __RNG_RELEASE_RESET __HAL_RCC_RNG_RELEASE_RESET // 释放 RNG 复位

/* SAI1 串行音频接口1 时钟控制 */
#define __SAI1_CLK_DISABLE __HAL_RCC_SAI1_CLK_DISABLE // 关闭 SAI1 时钟
#define __SAI1_CLK_ENABLE __HAL_RCC_SAI1_CLK_ENABLE // 使能 SAI1 时钟
#define __SAI1_CLK_SLEEP_DISABLE __HAL_RCC_SAI1_CLK_SLEEP_DISABLE // 睡眠模式下关闭 SAI1 时钟
#define __SAI1_CLK_SLEEP_ENABLE __HAL_RCC_SAI1_CLK_SLEEP_ENABLE // 睡眠模式下使能 SAI1 时钟
#define __SAI1_FORCE_RESET __HAL_RCC_SAI1_FORCE_RESET // 强制复位 SAI1
#define __SAI1_RELEASE_RESET __HAL_RCC_SAI1_RELEASE_RESET // 释放 SAI1 复位

/* SAI2 串行音频接口2 时钟控制 */
#define __SAI2_CLK_DISABLE __HAL_RCC_SAI2_CLK_DISABLE // 关闭 SAI2 时钟
#define __SAI2_CLK_ENABLE __HAL_RCC_SAI2_CLK_ENABLE // 使能 SAI2 时钟
#define __SAI2_CLK_SLEEP_DISABLE __HAL_RCC_SAI2_CLK_SLEEP_DISABLE // 睡眠模式下关闭 SAI2 时钟
#define __SAI2_CLK_SLEEP_ENABLE __HAL_RCC_SAI2_CLK_SLEEP_ENABLE // 睡眠模式下使能 SAI2 时钟
#define __SAI2_FORCE_RESET __HAL_RCC_SAI2_FORCE_RESET // 强制复位 SAI2
#define __SAI2_RELEASE_RESET __HAL_RCC_SAI2_RELEASE_RESET // 释放 SAI2 复位

/* SDIO 安全数字输入输出接口 时钟控制 */
#define __SDIO_CLK_DISABLE __HAL_RCC_SDIO_CLK_DISABLE // 关闭 SDIO 时钟
#define __SDIO_CLK_ENABLE __HAL_RCC_SDIO_CLK_ENABLE // 使能 SDIO 时钟

/* SDMMC 安全数字卡控制器 时钟控制 */
#define __SDMMC_CLK_DISABLE __HAL_RCC_SDMMC_CLK_DISABLE // 关闭 SDMMC 时钟
#define __SDMMC_CLK_ENABLE __HAL_RCC_SDMMC_CLK_ENABLE // 使能 SDMMC 时钟
#define __SDMMC_CLK_SLEEP_DISABLE __HAL_RCC_SDMMC_CLK_SLEEP_DISABLE // 睡眠模式下关闭 SDMMC 时钟
#define __SDMMC_CLK_SLEEP_ENABLE __HAL_RCC_SDMMC_CLK_SLEEP_ENABLE // 睡眠模式下使能 SDMMC 时钟
#define __SDMMC_FORCE_RESET __HAL_RCC_SDMMC_FORCE_RESET // 强制复位 SDMMC
#define __SDMMC_RELEASE_RESET __HAL_RCC_SDMMC_RELEASE_RESET // 释放 SDMMC 复位

/* SPI1 串行外设接口1 时钟控制 */
#define __SPI1_CLK_DISABLE __HAL_RCC_SPI1_CLK_DISABLE // 关闭 SPI1 时钟
#define __SPI1_CLK_ENABLE __HAL_RCC_SPI1_CLK_ENABLE // 使能 SPI1 时钟
#define __SPI1_CLK_SLEEP_DISABLE __HAL_RCC_SPI1_CLK_SLEEP_DISABLE // 睡眠模式下关闭 SPI1 时钟
#define __SPI1_CLK_SLEEP_ENABLE __HAL_RCC_SPI1_CLK_SLEEP_ENABLE // 睡眠模式下使能 SPI1 时钟
#define __SPI1_FORCE_RESET __HAL_RCC_SPI1_FORCE_RESET // 强制复位 SPI1
#define __SPI1_RELEASE_RESET __HAL_RCC_SPI1_RELEASE_RESET // 释放 SPI1 复位

/* SPI2 串行外设接口2 时钟控制 */
#define __SPI2_CLK_DISABLE __HAL_RCC_SPI2_CLK_DISABLE // 关闭 SPI2 时钟
#define __SPI2_CLK_ENABLE __HAL_RCC_SPI2_CLK_ENABLE // 使能 SPI2 时钟
#define __SPI2_CLK_SLEEP_DISABLE __HAL_RCC_SPI2_CLK_SLEEP_DISABLE // 睡眠模式下关闭 SPI2 时钟
#define __SPI2_CLK_SLEEP_ENABLE __HAL_RCC_SPI2_CLK_SLEEP_ENABLE // 睡眠模式下使能 SPI2 时钟
#define __SPI2_FORCE_RESET __HAL_RCC_SPI2_FORCE_RESET // 强制复位 SPI2
#define __SPI2_RELEASE_RESET __HAL_RCC_SPI2_RELEASE_RESET // 释放 SPI2 复位

/* SPI3 串行外设接口3 时钟控制 */
#define __SPI3_CLK_DISABLE __HAL_RCC_SPI3_CLK_DISABLE // 关闭 SPI3 时钟
#define __SPI3_CLK_ENABLE __HAL_RCC_SPI3_CLK_ENABLE // 使能 SPI3 时钟
#define __SPI3_CLK_SLEEP_DISABLE __HAL_RCC_SPI3_CLK_SLEEP_DISABLE // 睡眠模式下关闭 SPI3 时钟
#define __SPI3_CLK_SLEEP_ENABLE __HAL_RCC_SPI3_CLK_SLEEP_ENABLE // 睡眠模式下使能 SPI3 时钟
#define __SPI3_FORCE_RESET __HAL_RCC_SPI3_FORCE_RESET // 强制复位 SPI3
#define __SPI3_RELEASE_RESET __HAL_RCC_SPI3_RELEASE_RESET // 释放 SPI3 复位

/* SRAM 静态随机存取存储器 时钟控制 */
#define __SRAM_CLK_DISABLE __HAL_RCC_SRAM_CLK_DISABLE // 关闭 SRAM 时钟
#define __SRAM_CLK_ENABLE __HAL_RCC_SRAM_CLK_ENABLE // 使能 SRAM 时钟
#define __SRAM1_CLK_SLEEP_DISABLE __HAL_RCC_SRAM1_CLK_SLEEP_DISABLE // 睡眠模式下关闭 SRAM1 时钟
#define __SRAM1_CLK_SLEEP_ENABLE __HAL_RCC_SRAM1_CLK_SLEEP_ENABLE // 睡眠模式下使能 SRAM1 时钟
#define __SRAM2_CLK_SLEEP_DISABLE __HAL_RCC_SRAM2_CLK_SLEEP_DISABLE // 睡眠模式下关闭 SRAM2 时钟
#define __SRAM2_CLK_SLEEP_ENABLE __HAL_RCC_SRAM2_CLK_SLEEP_ENABLE // 睡眠模式下使能 SRAM2 时钟

/* SWPMI1 单线协议接口1 时钟控制 */
#define __SWPMI1_CLK_DISABLE __HAL_RCC_SWPMI1_CLK_DISABLE // 关闭 SWPMI1 时钟
#define __SWPMI1_CLK_ENABLE __HAL_RCC_SWPMI1_CLK_ENABLE // 使能 SWPMI1 时钟
#define __SWPMI1_CLK_SLEEP_DISABLE __HAL_RCC_SWPMI1_CLK_SLEEP_DISABLE // 睡眠模式下关闭 SWPMI1 时钟
#define __SWPMI1_CLK_SLEEP_ENABLE __HAL_RCC_SWPMI1_CLK_SLEEP_ENABLE // 睡眠模式下使能 SWPMI1 时钟
#define __SWPMI1_FORCE_RESET __HAL_RCC_SWPMI1_FORCE_RESET // 强制复位 SWPMI1
#define __SWPMI1_RELEASE_RESET __HAL_RCC_SWPMI1_RELEASE_RESET // 释放 SWPMI1 复位

/* SYSCFG 系统配置控制器 时钟控制 */
#define __SYSCFG_CLK_DISABLE __HAL_RCC_SYSCFG_CLK_DISABLE // 关闭 SYSCFG 时钟
#define __SYSCFG_CLK_ENABLE __HAL_RCC_SYSCFG_CLK_ENABLE // 使能 SYSCFG 时钟
#define __SYSCFG_CLK_SLEEP_DISABLE __HAL_RCC_SYSCFG_CLK_SLEEP_DISABLE // 睡眠模式下关闭 SYSCFG 时钟
#define __SYSCFG_CLK_SLEEP_ENABLE __HAL_RCC_SYSCFG_CLK_SLEEP_ENABLE // 睡眠模式下使能 SYSCFG 时钟
#define __SYSCFG_FORCE_RESET __HAL_RCC_SYSCFG_FORCE_RESET // 强制复位 SYSCFG
#define __SYSCFG_RELEASE_RESET __HAL_RCC_SYSCFG_RELEASE_RESET // 释放 SYSCFG 复位

/* TIM1 高级定时器1 时钟控制 */
#define __TIM1_CLK_DISABLE __HAL_RCC_TIM1_CLK_DISABLE // 关闭 TIM1 时钟
#define __TIM1_CLK_ENABLE __HAL_RCC_TIM1_CLK_ENABLE // 使能 TIM1 时钟
#define __TIM1_CLK_SLEEP_DISABLE __HAL_RCC_TIM1_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM1 时钟
#define __TIM1_CLK_SLEEP_ENABLE __HAL_RCC_TIM1_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM1 时钟
#define __TIM1_FORCE_RESET __HAL_RCC_TIM1_FORCE_RESET // 强制复位 TIM1
#define __TIM1_RELEASE_RESET __HAL_RCC_TIM1_RELEASE_RESET // 释放 TIM1 复位

/* TIM10 通用定时器10 时钟控制 */
#define __TIM10_CLK_DISABLE __HAL_RCC_TIM10_CLK_DISABLE // 关闭 TIM10 时钟
#define __TIM10_CLK_ENABLE __HAL_RCC_TIM10_CLK_ENABLE // 使能 TIM10 时钟
#define __TIM10_FORCE_RESET __HAL_RCC_TIM10_FORCE_RESET // 强制复位 TIM10
#define __TIM10_RELEASE_RESET __HAL_RCC_TIM10_RELEASE_RESET // 释放 TIM10 复位

/* TIM11 通用定时器11 时钟控制 */
#define __TIM11_CLK_DISABLE __HAL_RCC_TIM11_CLK_DISABLE // 关闭 TIM11 时钟
#define __TIM11_CLK_ENABLE __HAL_RCC_TIM11_CLK_ENABLE // 使能 TIM11 时钟
#define __TIM11_FORCE_RESET __HAL_RCC_TIM11_FORCE_RESET // 强制复位 TIM11
#define __TIM11_RELEASE_RESET __HAL_RCC_TIM11_RELEASE_RESET // 释放 TIM11 复位

/* TIM12 通用定时器12 时钟控制 */
#define __TIM12_CLK_DISABLE __HAL_RCC_TIM12_CLK_DISABLE // 关闭 TIM12 时钟
#define __TIM12_CLK_ENABLE __HAL_RCC_TIM12_CLK_ENABLE // 使能 TIM12 时钟
#define __TIM12_FORCE_RESET __HAL_RCC_TIM12_FORCE_RESET // 强制复位 TIM12
#define __TIM12_RELEASE_RESET __HAL_RCC_TIM12_RELEASE_RESET // 释放 TIM12 复位

/* TIM13 通用定时器13 时钟控制 */
#define __TIM13_CLK_DISABLE __HAL_RCC_TIM13_CLK_DISABLE // 关闭 TIM13 时钟
#define __TIM13_CLK_ENABLE __HAL_RCC_TIM13_CLK_ENABLE // 使能 TIM13 时钟
#define __TIM13_FORCE_RESET __HAL_RCC_TIM13_FORCE_RESET // 强制复位 TIM13
#define __TIM13_RELEASE_RESET __HAL_RCC_TIM13_RELEASE_RESET // 释放 TIM13 复位

/* TIM14 通用定时器14 时钟控制 */
#define __TIM14_CLK_DISABLE __HAL_RCC_TIM14_CLK_DISABLE // 关闭 TIM14 时钟
#define __TIM14_CLK_ENABLE __HAL_RCC_TIM14_CLK_ENABLE // 使能 TIM14 时钟
#define __TIM14_FORCE_RESET __HAL_RCC_TIM14_FORCE_RESET // 强制复位 TIM14
#define __TIM14_RELEASE_RESET __HAL_RCC_TIM14_RELEASE_RESET // 释放 TIM14 复位

/* TIM15 通用定时器15 时钟控制 */
#define __TIM15_CLK_DISABLE __HAL_RCC_TIM15_CLK_DISABLE // 关闭 TIM15 时钟
#define __TIM15_CLK_ENABLE __HAL_RCC_TIM15_CLK_ENABLE // 使能 TIM15 时钟
#define __TIM15_CLK_SLEEP_DISABLE __HAL_RCC_TIM15_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM15 时钟
#define __TIM15_CLK_SLEEP_ENABLE __HAL_RCC_TIM15_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM15 时钟
#define __TIM15_FORCE_RESET __HAL_RCC_TIM15_FORCE_RESET // 强制复位 TIM15
#define __TIM15_RELEASE_RESET __HAL_RCC_TIM15_RELEASE_RESET // 释放 TIM15 复位

/* TIM16 通用定时器16 时钟控制 */
#define __TIM16_CLK_DISABLE __HAL_RCC_TIM16_CLK_DISABLE // 关闭 TIM16 时钟
#define __TIM16_CLK_ENABLE __HAL_RCC_TIM16_CLK_ENABLE // 使能 TIM16 时钟
#define __TIM16_CLK_SLEEP_DISABLE __HAL_RCC_TIM16_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM16 时钟
#define __TIM16_CLK_SLEEP_ENABLE __HAL_RCC_TIM16_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM16 时钟
#define __TIM16_FORCE_RESET __HAL_RCC_TIM16_FORCE_RESET // 强制复位 TIM16
#define __TIM16_RELEASE_RESET __HAL_RCC_TIM16_RELEASE_RESET // 释放 TIM16 复位

/* TIM17 通用定时器17 时钟控制 */
#define __TIM17_CLK_DISABLE __HAL_RCC_TIM17_CLK_DISABLE // 关闭 TIM17 时钟
#define __TIM17_CLK_ENABLE __HAL_RCC_TIM17_CLK_ENABLE // 使能 TIM17 时钟
#define __TIM17_CLK_SLEEP_DISABLE __HAL_RCC_TIM17_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM17 时钟
#define __TIM17_CLK_SLEEP_ENABLE __HAL_RCC_TIM17_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM17 时钟
#define __TIM17_FORCE_RESET __HAL_RCC_TIM17_FORCE_RESET // 强制复位 TIM17
#define __TIM17_RELEASE_RESET __HAL_RCC_TIM17_RELEASE_RESET // 释放 TIM17 复位

/* TIM2 通用定时器2 时钟控制 */
#define __TIM2_CLK_DISABLE __HAL_RCC_TIM2_CLK_DISABLE // 关闭 TIM2 时钟
#define __TIM2_CLK_ENABLE __HAL_RCC_TIM2_CLK_ENABLE // 使能 TIM2 时钟
#define __TIM2_CLK_SLEEP_DISABLE __HAL_RCC_TIM2_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM2 时钟
#define __TIM2_CLK_SLEEP_ENABLE __HAL_RCC_TIM2_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM2 时钟
#define __TIM2_FORCE_RESET __HAL_RCC_TIM2_FORCE_RESET // 强制复位 TIM2
#define __TIM2_RELEASE_RESET __HAL_RCC_TIM2_RELEASE_RESET // 释放 TIM2 复位

/* TIM3 通用定时器3 时钟控制 */
#define __TIM3_CLK_DISABLE __HAL_RCC_TIM3_CLK_DISABLE // 关闭 TIM3 时钟
#define __TIM3_CLK_ENABLE __HAL_RCC_TIM3_CLK_ENABLE // 使能 TIM3 时钟
#define __TIM3_CLK_SLEEP_DISABLE __HAL_RCC_TIM3_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM3 时钟
#define __TIM3_CLK_SLEEP_ENABLE __HAL_RCC_TIM3_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM3 时钟
#define __TIM3_FORCE_RESET __HAL_RCC_TIM3_FORCE_RESET // 强制复位 TIM3
#define __TIM3_RELEASE_RESET __HAL_RCC_TIM3_RELEASE_RESET // 释放 TIM3 复位

/* TIM4 通用定时器4 时钟控制 */
#define __TIM4_CLK_DISABLE __HAL_RCC_TIM4_CLK_DISABLE // 关闭 TIM4 时钟
#define __TIM4_CLK_ENABLE __HAL_RCC_TIM4_CLK_ENABLE // 使能 TIM4 时钟
#define __TIM4_CLK_SLEEP_DISABLE __HAL_RCC_TIM4_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM4 时钟
#define __TIM4_CLK_SLEEP_ENABLE __HAL_RCC_TIM4_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM4 时钟
#define __TIM4_FORCE_RESET __HAL_RCC_TIM4_FORCE_RESET // 强制复位 TIM4
#define __TIM4_RELEASE_RESET __HAL_RCC_TIM4_RELEASE_RESET // 释放 TIM4 复位

/* TIM5 通用定时器5 时钟控制 */
#define __TIM5_CLK_DISABLE __HAL_RCC_TIM5_CLK_DISABLE // 关闭 TIM5 时钟
#define __TIM5_CLK_ENABLE __HAL_RCC_TIM5_CLK_ENABLE // 使能 TIM5 时钟
#define __TIM5_CLK_SLEEP_DISABLE __HAL_RCC_TIM5_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM5 时钟
#define __TIM5_CLK_SLEEP_ENABLE __HAL_RCC_TIM5_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM5 时钟
#define __TIM5_FORCE_RESET __HAL_RCC_TIM5_FORCE_RESET // 强制复位 TIM5
#define __TIM5_RELEASE_RESET __HAL_RCC_TIM5_RELEASE_RESET // 释放 TIM5 复位

/* TIM6 基本定时器6 时钟控制 */
#define __TIM6_CLK_DISABLE __HAL_RCC_TIM6_CLK_DISABLE // 关闭 TIM6 时钟
#define __TIM6_CLK_ENABLE __HAL_RCC_TIM6_CLK_ENABLE // 使能 TIM6 时钟
#define __TIM6_CLK_SLEEP_DISABLE __HAL_RCC_TIM6_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM6 时钟
#define __TIM6_CLK_SLEEP_ENABLE __HAL_RCC_TIM6_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM6 时钟
#define __TIM6_FORCE_RESET __HAL_RCC_TIM6_FORCE_RESET // 强制复位 TIM6
#define __TIM6_RELEASE_RESET __HAL_RCC_TIM6_RELEASE_RESET // 释放 TIM6 复位

/* TIM7 基本定时器7 时钟控制 */
#define __TIM7_CLK_DISABLE __HAL_RCC_TIM7_CLK_DISABLE // 关闭 TIM7 时钟
#define __TIM7_CLK_ENABLE __HAL_RCC_TIM7_CLK_ENABLE // 使能 TIM7 时钟
#define __TIM7_CLK_SLEEP_DISABLE __HAL_RCC_TIM7_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM7 时钟
#define __TIM7_CLK_SLEEP_ENABLE __HAL_RCC_TIM7_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM7 时钟
#define __TIM7_FORCE_RESET __HAL_RCC_TIM7_FORCE_RESET // 强制复位 TIM7
#define __TIM7_RELEASE_RESET __HAL_RCC_TIM7_RELEASE_RESET // 释放 TIM7 复位

/* TIM8 高级定时器8 时钟控制 */
#define __TIM8_CLK_DISABLE __HAL_RCC_TIM8_CLK_DISABLE // 关闭 TIM8 时钟
#define __TIM8_CLK_ENABLE __HAL_RCC_TIM8_CLK_ENABLE // 使能 TIM8 时钟
#define __TIM8_CLK_SLEEP_DISABLE __HAL_RCC_TIM8_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM8 时钟
#define __TIM8_CLK_SLEEP_ENABLE __HAL_RCC_TIM8_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM8 时钟
#define __TIM8_FORCE_RESET __HAL_RCC_TIM8_FORCE_RESET // 强制复位 TIM8
#define __TIM8_RELEASE_RESET __HAL_RCC_TIM8_RELEASE_RESET // 释放 TIM8 复位

/* TIM9 通用定时器9 时钟控制 */
#define __TIM9_CLK_DISABLE __HAL_RCC_TIM9_CLK_DISABLE // 关闭 TIM9 时钟
#define __TIM9_CLK_ENABLE __HAL_RCC_TIM9_CLK_ENABLE // 使能 TIM9 时钟
#define __TIM9_FORCE_RESET __HAL_RCC_TIM9_FORCE_RESET // 强制复位 TIM9
#define __TIM9_RELEASE_RESET __HAL_RCC_TIM9_RELEASE_RESET // 释放 TIM9 复位

/* TSC 触摸传感控制器 时钟控制 */
#define __TSC_CLK_DISABLE __HAL_RCC_TSC_CLK_DISABLE // 关闭 TSC 时钟
#define __TSC_CLK_ENABLE __HAL_RCC_TSC_CLK_ENABLE // 使能 TSC 时钟
#define __TSC_CLK_SLEEP_DISABLE __HAL_RCC_TSC_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TSC 时钟
#define __TSC_CLK_SLEEP_ENABLE __HAL_RCC_TSC_CLK_SLEEP_ENABLE // 睡眠模式下使能 TSC 时钟
#define __TSC_FORCE_RESET __HAL_RCC_TSC_FORCE_RESET // 强制复位 TSC
#define __TSC_RELEASE_RESET __HAL_RCC_TSC_RELEASE_RESET // 释放 TSC 复位

/* UART4 通用异步收发器4 时钟控制 */
#define __UART4_CLK_DISABLE __HAL_RCC_UART4_CLK_DISABLE // 关闭 UART4 时钟
#define __UART4_CLK_ENABLE __HAL_RCC_UART4_CLK_ENABLE // 使能 UART4 时钟
#define __UART4_CLK_SLEEP_DISABLE __HAL_RCC_UART4_CLK_SLEEP_DISABLE // 睡眠模式下关闭 UART4 时钟
#define __UART4_CLK_SLEEP_ENABLE __HAL_RCC_UART4_CLK_SLEEP_ENABLE // 睡眠模式下使能 UART4 时钟
#define __UART4_FORCE_RESET __HAL_RCC_UART4_FORCE_RESET // 强制复位 UART4
#define __UART4_RELEASE_RESET __HAL_RCC_UART4_RELEASE_RESET // 释放 UART4 复位

/* UART5 通用异步收发器5 时钟控制 */
#define __UART5_CLK_DISABLE __HAL_RCC_UART5_CLK_DISABLE // 关闭 UART5 时钟
#define __UART5_CLK_ENABLE __HAL_RCC_UART5_CLK_ENABLE // 使能 UART5 时钟
#define __UART5_CLK_SLEEP_DISABLE __HAL_RCC_UART5_CLK_SLEEP_DISABLE // 睡眠模式下关闭 UART5 时钟
#define __UART5_CLK_SLEEP_ENABLE __HAL_RCC_UART5_CLK_SLEEP_ENABLE // 睡眠模式下使能 UART5 时钟
#define __UART5_FORCE_RESET __HAL_RCC_UART5_FORCE_RESET // 强制复位 UART5
#define __UART5_RELEASE_RESET __HAL_RCC_UART5_RELEASE_RESET // 释放 UART5 复位

/* USART1 通用同步/异步收发器1 时钟控制 */
#define __USART1_CLK_DISABLE __HAL_RCC_USART1_CLK_DISABLE // 关闭 USART1 时钟
#define __USART1_CLK_ENABLE __HAL_RCC_USART1_CLK_ENABLE // 使能 USART1 时钟
#define __USART1_CLK_SLEEP_DISABLE __HAL_RCC_USART1_CLK_SLEEP_DISABLE // 睡眠模式下关闭 USART1 时钟
#define __USART1_CLK_SLEEP_ENABLE __HAL_RCC_USART1_CLK_SLEEP_ENABLE // 睡眠模式下使能 USART1 时钟
#define __USART1_FORCE_RESET __HAL_RCC_USART1_FORCE_RESET // 强制复位 USART1
#define __USART1_RELEASE_RESET __HAL_RCC_USART1_RELEASE_RESET // 释放 USART1 复位

/* USART2 通用同步/异步收发器2 时钟控制 */
#define __USART2_CLK_DISABLE __HAL_RCC_USART2_CLK_DISABLE // 关闭 USART2 时钟
#define __USART2_CLK_ENABLE __HAL_RCC_USART2_CLK_ENABLE // 使能 USART2 时钟
#define __USART2_CLK_SLEEP_DISABLE __HAL_RCC_USART2_CLK_SLEEP_DISABLE // 睡眠模式下关闭 USART2 时钟
#define __USART2_CLK_SLEEP_ENABLE __HAL_RCC_USART2_CLK_SLEEP_ENABLE // 睡眠模式下使能 USART2 时钟
#define __USART2_FORCE_RESET __HAL_RCC_USART2_FORCE_RESET // 强制复位 USART2
#define __USART2_RELEASE_RESET __HAL_RCC_USART2_RELEASE_RESET // 释放 USART2 复位

/* USART3 通用同步/异步收发器3 时钟控制 */
#define __USART3_CLK_DISABLE __HAL_RCC_USART3_CLK_DISABLE // 关闭 USART3 时钟
#define __USART3_CLK_ENABLE __HAL_RCC_USART3_CLK_ENABLE // 使能 USART3 时钟
#define __USART3_CLK_SLEEP_DISABLE __HAL_RCC_USART3_CLK_SLEEP_DISABLE // 睡眠模式下关闭 USART3 时钟
#define __USART3_CLK_SLEEP_ENABLE __HAL_RCC_USART3_CLK_SLEEP_ENABLE // 睡眠模式下使能 USART3 时钟
#define __USART3_FORCE_RESET __HAL_RCC_USART3_FORCE_RESET // 强制复位 USART3
#define __USART3_RELEASE_RESET __HAL_RCC_USART3_RELEASE_RESET // 释放 USART3 复位

/* USART4 通用同步/异步收发器4 时钟控制 (映射到 UART4) */
#define __USART4_CLK_DISABLE        __HAL_RCC_UART4_CLK_DISABLE // 关闭 USART4 时钟
#define __USART4_CLK_ENABLE         __HAL_RCC_UART4_CLK_ENABLE // 使能 USART4 时钟
#define __USART4_CLK_SLEEP_ENABLE   __HAL_RCC_UART4_CLK_SLEEP_ENABLE // 睡眠模式下使能 USART4 时钟
#define __USART4_CLK_SLEEP_DISABLE  __HAL_RCC_UART4_CLK_SLEEP_DISABLE // 睡眠模式下关闭 USART4 时钟
#define __USART4_FORCE_RESET        __HAL_RCC_UART4_FORCE_RESET // 强制复位 USART4
#define __USART4_RELEASE_RESET      __HAL_RCC_UART4_RELEASE_RESET // 释放 USART4 复位

/* USART5 通用同步/异步收发器5 时钟控制 (映射到 UART5) */
#define __USART5_CLK_DISABLE        __HAL_RCC_UART5_CLK_DISABLE // 关闭 USART5 时钟
#define __USART5_CLK_ENABLE         __HAL_RCC_UART5_CLK_ENABLE // 使能 USART5 时钟
#define __USART5_CLK_SLEEP_ENABLE   __HAL_RCC_UART5_CLK_SLEEP_ENABLE // 睡眠模式下使能 USART5 时钟
#define __USART5_CLK_SLEEP_DISABLE  __HAL_RCC_UART5_CLK_SLEEP_DISABLE // 睡眠模式下关闭 USART5 时钟
#define __USART5_FORCE_RESET        __HAL_RCC_UART5_FORCE_RESET // 强制复位 USART5
#define __USART5_RELEASE_RESET      __HAL_RCC_UART5_RELEASE_RESET // 释放 USART5 复位

/* USART7 通用同步/异步收发器7 时钟控制 */
#define __USART7_CLK_DISABLE        __HAL_RCC_UART7_CLK_DISABLE // 关闭 USART7 时钟
#define __USART7_CLK_ENABLE         __HAL_RCC_UART7_CLK_ENABLE // 使能 USART7 时钟
#define __USART7_FORCE_RESET        __HAL_RCC_UART7_FORCE_RESET // 强制复位 USART7
#define __USART7_RELEASE_RESET      __HAL_RCC_UART7_RELEASE_RESET // 释放 USART7 复位

/* USART8 通用同步/异步收发器8 时钟控制 */
#define __USART8_CLK_DISABLE        __HAL_RCC_UART8_CLK_DISABLE // 关闭 USART8 时钟
#define __USART8_CLK_ENABLE         __HAL_RCC_UART8_CLK_ENABLE // 使能 USART8 时钟
#define __USART8_FORCE_RESET        __HAL_RCC_UART8_FORCE_RESET // 强制复位 USART8
#define __USART8_RELEASE_RESET      __HAL_RCC_UART8_RELEASE_RESET // 释放 USART8 复位

/* USB 通用串行总线 时钟控制 */
#define __USB_CLK_DISABLE         __HAL_RCC_USB_CLK_DISABLE // 关闭 USB 时钟
#define __USB_CLK_ENABLE          __HAL_RCC_USB_CLK_ENABLE // 使能 USB 时钟
#define __USB_FORCE_RESET         __HAL_RCC_USB_FORCE_RESET // 强制复位 USB
#define __USB_CLK_SLEEP_ENABLE    __HAL_RCC_USB_CLK_SLEEP_ENABLE // 睡眠模式下使能 USB 时钟
#define __USB_CLK_SLEEP_DISABLE   __HAL_RCC_USB_CLK_SLEEP_DISABLE // 睡眠模式下关闭 USB 时钟

/* USB_OTG_FS USB全速OTG控制器 时钟控制 */
#define __USB_OTG_FS_CLK_DISABLE __HAL_RCC_USB_OTG_FS_CLK_DISABLE // 关闭 USB OTG FS 时钟
#define __USB_OTG_FS_CLK_ENABLE __HAL_RCC_USB_OTG_FS_CLK_ENABLE // 使能 USB OTG FS 时钟
#define __USB_RELEASE_RESET __HAL_RCC_USB_RELEASE_RESET // 释放 USB 复位

/* 针对 STM32H7 系列的特殊定义 */
#if defined(STM32H7)
/* WWDG 窗口看门狗 时钟控制 (映射到 WWDG1) */
#define __HAL_RCC_WWDG_CLK_DISABLE   __HAL_RCC_WWDG1_CLK_DISABLE // 关闭 WWDG 时钟
#define __HAL_RCC_WWDG_CLK_ENABLE   __HAL_RCC_WWDG1_CLK_ENABLE // 使能 WWDG 时钟
#define __HAL_RCC_WWDG_CLK_SLEEP_DISABLE  __HAL_RCC_WWDG1_CLK_SLEEP_DISABLE // 睡眠模式下关闭 WWDG 时钟
#define __HAL_RCC_WWDG_CLK_SLEEP_ENABLE  __HAL_RCC_WWDG1_CLK_SLEEP_ENABLE // 睡眠模式下使能 WWDG 时钟

/* STM32H7 系列不支持独立强制/释放复位 WWDG，定义为空操作 */
#define __HAL_RCC_WWDG_FORCE_RESET    ((void)0U)  /* STM32H7 上不可用 */
#define __HAL_RCC_WWDG_RELEASE_RESET ((void)0U) /* STM32H7 上不可用 */


/* WWDG 时钟状态检查宏 */
#define  __HAL_RCC_WWDG_IS_CLK_ENABLED    __HAL_RCC_WWDG1_IS_CLK_ENABLED // 检查 WWDG 时钟是否已使能
#define  __HAL_RCC_WWDG_IS_CLK_DISABLED  __HAL_RCC_WWDG1_IS_CLK_DISABLED // 检查 WWDG 时钟是否已关闭

/* SPI 时钟源映射定义 (用于兼容性) */
#define  RCC_SPI4CLKSOURCE_D2PCLK1       RCC_SPI4CLKSOURCE_D2PCLK2 // SPI4 时钟源映射
#define  RCC_SPI5CLKSOURCE_D2PCLK1       RCC_SPI5CLKSOURCE_D2PCLK2 // SPI5 时钟源映射
#define  RCC_SPI45CLKSOURCE_D2PCLK1      RCC_SPI45CLKSOURCE_D2PCLK2 // SPI4/5 时钟源映射
#define  RCC_SPI45CLKSOURCE_CDPCLK1      RCC_SPI45CLKSOURCE_CDPCLK2 // SPI4/5 时钟源映射
#define  RCC_SPI45CLKSOURCE_PCLK1        RCC_SPI45CLKSOURCE_PCLK2 // SPI4/5 时钟源映射
#endif

/* WWDG 窗口看门狗 时钟控制 (通用定义) */
#define __WWDG_CLK_DISABLE __HAL_RCC_WWDG_CLK_DISABLE // 关闭 WWDG 时钟
#define __WWDG_CLK_ENABLE __HAL_RCC_WWDG_CLK_ENABLE // 使能 WWDG 时钟
#define __WWDG_CLK_SLEEP_DISABLE __HAL_RCC_WWDG_CLK_SLEEP_DISABLE // 睡眠模式下关闭 WWDG 时钟
#define __WWDG_CLK_SLEEP_ENABLE __HAL_RCC_WWDG_CLK_SLEEP_ENABLE // 睡眠模式下使能 WWDG 时钟
#define __WWDG_FORCE_RESET __HAL_RCC_WWDG_FORCE_RESET // 强制复位 WWDG
#define __WWDG_RELEASE_RESET __HAL_RCC_WWDG_RELEASE_RESET // 释放 WWDG 复位

/* TIM21 通用定时器21 时钟控制 */
#define __TIM21_CLK_ENABLE   __HAL_RCC_TIM21_CLK_ENABLE // 使能 TIM21 时钟
#define __TIM21_CLK_DISABLE   __HAL_RCC_TIM21_CLK_DISABLE // 关闭 TIM21 时钟
#define __TIM21_FORCE_RESET   __HAL_RCC_TIM21_FORCE_RESET // 强制复位 TIM21
#define __TIM21_RELEASE_RESET  __HAL_RCC_TIM21_RELEASE_RESET // 释放 TIM21 复位
#define __TIM21_CLK_SLEEP_ENABLE   __HAL_RCC_TIM21_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM21 时钟
#define __TIM21_CLK_SLEEP_DISABLE   __HAL_RCC_TIM21_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM21 时钟

/* TIM22 通用定时器22 时钟控制 */
#define __TIM22_CLK_ENABLE   __HAL_RCC_TIM22_CLK_ENABLE // 使能 TIM22 时钟
#define __TIM22_CLK_DISABLE   __HAL_RCC_TIM22_CLK_DISABLE // 关闭 TIM22 时钟
#define __TIM22_FORCE_RESET   __HAL_RCC_TIM22_FORCE_RESET // 强制复位 TIM22
#define __TIM22_RELEASE_RESET  __HAL_RCC_TIM22_RELEASE_RESET // 释放 TIM22 复位
#define __TIM22_CLK_SLEEP_ENABLE   __HAL_RCC_TIM22_CLK_SLEEP_ENABLE // 睡眠模式下使能 TIM22 时钟
#define __TIM22_CLK_SLEEP_DISABLE   __HAL_RCC_TIM22_CLK_SLEEP_DISABLE // 睡眠模式下关闭 TIM22 时钟

/* CRS 时钟恢复系统 时钟控制 */
#define __CRS_CLK_DISABLE __HAL_RCC_CRS_CLK_DISABLE // 关闭 CRS 时钟
#define __CRS_CLK_ENABLE __HAL_RCC_CRS_CLK_ENABLE // 使能 CRS 时钟
#define __CRS_CLK_SLEEP_DISABLE __HAL_RCC_CRS_CLK_SLEEP_DISABLE // 睡眠模式下关闭 CRS 时钟
#define __CRS_CLK_SLEEP_ENABLE __HAL_RCC_CRS_CLK_SLEEP_ENABLE // 睡眠模式下使能 CRS 时钟
#define __CRS_FORCE_RESET __HAL_RCC_CRS_FORCE_RESET // 强制复位 CRS
#define __CRS_RELEASE_RESET __HAL_RCC_CRS_RELEASE_RESET // 释放 CRS 复位

/* RCC 备份域复位控制 */
#define __RCC_BACKUPRESET_FORCE __HAL_RCC_BACKUPRESET_FORCE // 强制备份域复位
#define __RCC_BACKUPRESET_RELEASE __HAL_RCC_BACKUPRESET_RELEASE // 释放备份域复位
