/* USB OTG FS 全速模式外设复位控制宏定义 */
#define __USB_OTG_FS_FORCE_RESET  __HAL_RCC_USB_OTG_FS_FORCE_RESET // 强制复位USB OTG全速模式外设
#define __USB_OTG_FS_RELEASE_RESET  __HAL_RCC_USB_OTG_FS_RELEASE_RESET // 释放复位USB OTG全速模式外设

/* USB OTG FS 睡眠模式时钟控制宏定义 */
#define __USB_OTG_FS_CLK_SLEEP_ENABLE  __HAL_RCC_USB_OTG_FS_CLK_SLEEP_ENABLE // 使能USB OTG FS睡眠模式时钟
#define __USB_OTG_FS_CLK_SLEEP_DISABLE  __HAL_RCC_USB_OTG_FS_CLK_SLEEP_DISABLE // 禁止USB OTG FS睡眠模式时钟

/* USB OTG HS 高速模式外设时钟控制宏定义 */
#define __USB_OTG_HS_CLK_DISABLE  __HAL_RCC_USB_OTG_HS_CLK_DISABLE // 禁止USB OTG高速模式外设时钟
#define __USB_OTG_HS_CLK_ENABLE          __HAL_RCC_USB_OTG_HS_CLK_ENABLE // 使能USB OTG高速模式外设时钟

/* USB OTG HS ULPI接口时钟控制宏定义 (用于外部PHY) */
#define __USB_OTG_HS_ULPI_CLK_ENABLE  __HAL_RCC_USB_OTG_HS_ULPI_CLK_ENABLE // 使能USB OTG HS ULPI时钟
#define __USB_OTG_HS_ULPI_CLK_DISABLE  __HAL_RCC_USB_OTG_HS_ULPI_CLK_DISABLE // 禁止USB OTG HS ULPI时钟

/* 定时器9睡眠模式时钟控制宏定义 */
#define __TIM9_CLK_SLEEP_ENABLE          __HAL_RCC_TIM9_CLK_SLEEP_ENABLE // 使能TIM9睡眠模式时钟
#define __TIM9_CLK_SLEEP_DISABLE  __HAL_RCC_TIM9_CLK_SLEEP_DISABLE // 禁止TIM9睡眠模式时钟

/* 定时器10睡眠模式时钟控制宏定义 */
#define __TIM10_CLK_SLEEP_ENABLE  __HAL_RCC_TIM10_CLK_SLEEP_ENABLE // 使能TIM10睡眠模式时钟
#define __TIM10_CLK_SLEEP_DISABLE  __HAL_RCC_TIM10_CLK_SLEEP_DISABLE // 禁止TIM10睡眠模式时钟

/* 定时器11睡眠模式时钟控制宏定义 */
#define __TIM11_CLK_SLEEP_ENABLE  __HAL_RCC_TIM11_CLK_SLEEP_ENABLE // 使能TIM11睡眠模式时钟
#define __TIM11_CLK_SLEEP_DISABLE  __HAL_RCC_TIM11_CLK_SLEEP_DISABLE // 禁止TIM11睡眠模式时钟

/* 以太网PTP时钟控制宏定义 */
#define __ETHMACPTP_CLK_SLEEP_ENABLE  __HAL_RCC_ETHMACPTP_CLK_SLEEP_ENABLE // 使能以太网MAC PTP睡眠模式时钟
#define __ETHMACPTP_CLK_SLEEP_DISABLE  __HAL_RCC_ETHMACPTP_CLK_SLEEP_DISABLE // 禁止以太网MAC PTP睡眠模式时钟
#define __ETHMACPTP_CLK_ENABLE          __HAL_RCC_ETHMACPTP_CLK_ENABLE // 使能以太网MAC PTP时钟
#define __ETHMACPTP_CLK_DISABLE          __HAL_RCC_ETHMACPTP_CLK_DISABLE // 禁止以太网MAC PTP时钟

/* HASH硬件哈希加速器时钟控制宏定义 */
#define __HASH_CLK_ENABLE          __HAL_RCC_HASH_CLK_ENABLE // 使能HASH外设时钟
#define __HASH_FORCE_RESET          __HAL_RCC_HASH_FORCE_RESET // 强制复位HASH外设
#define __HASH_RELEASE_RESET          __HAL_RCC_HASH_RELEASE_RESET // 释放复位HASH外设
#define __HASH_CLK_SLEEP_ENABLE          __HAL_RCC_HASH_CLK_SLEEP_ENABLE // 使能HASH睡眠模式时钟
#define __HASH_CLK_SLEEP_DISABLE  __HAL_RCC_HASH_CLK_SLEEP_DISABLE // 禁止HASH睡眠模式时钟
#define __HASH_CLK_DISABLE            __HAL_RCC_HASH_CLK_DISABLE // 禁止HASH外设时钟

/* SPI5串行外设接口时钟控制宏定义 */
#define __SPI5_CLK_ENABLE          __HAL_RCC_SPI5_CLK_ENABLE // 使能SPI5时钟
#define __SPI5_CLK_DISABLE              __HAL_RCC_SPI5_CLK_DISABLE // 禁止SPI5时钟
#define __SPI5_FORCE_RESET          __HAL_RCC_SPI5_FORCE_RESET // 强制复位SPI5
#define __SPI5_RELEASE_RESET          __HAL_RCC_SPI5_RELEASE_RESET // 释放复位SPI5
#define __SPI5_CLK_SLEEP_ENABLE          __HAL_RCC_SPI5_CLK_SLEEP_ENABLE // 使能SPI5睡眠模式时钟
#define __SPI5_CLK_SLEEP_DISABLE  __HAL_RCC_SPI5_CLK_SLEEP_DISABLE // 禁止SPI5睡眠模式时钟

/* SPI6串行外设接口时钟控制宏定义 */
#define __SPI6_CLK_ENABLE          __HAL_RCC_SPI6_CLK_ENABLE // 使能SPI6时钟
#define __SPI6_CLK_DISABLE          __HAL_RCC_SPI6_CLK_DISABLE // 禁止SPI6时钟
#define __SPI6_FORCE_RESET          __HAL_RCC_SPI6_FORCE_RESET // 强制复位SPI6
#define __SPI6_RELEASE_RESET         __HAL_RCC_SPI6_RELEASE_RESET // 释放复位SPI6
#define __SPI6_CLK_SLEEP_ENABLE          __HAL_RCC_SPI6_CLK_SLEEP_ENABLE // 使能SPI6睡眠模式时钟
#define __SPI6_CLK_SLEEP_DISABLE  __HAL_RCC_SPI6_CLK_SLEEP_DISABLE // 禁止SPI6睡眠模式时钟

/* LTDC液晶显示控制器时钟控制宏定义 */
#define __LTDC_CLK_ENABLE          __HAL_RCC_LTDC_CLK_ENABLE // 使能LTDC时钟
#define __LTDC_CLK_DISABLE          __HAL_RCC_LTDC_CLK_DISABLE // 禁止LTDC时钟
#define __LTDC_FORCE_RESET          __HAL_RCC_LTDC_FORCE_RESET // 强制复位LTDC
#define __LTDC_RELEASE_RESET          __HAL_RCC_LTDC_RELEASE_RESET // 释放复位LTDC
#define __LTDC_CLK_SLEEP_ENABLE          __HAL_RCC_LTDC_CLK_SLEEP_ENABLE // 使能LTDC睡眠模式时钟

/* 以太网MAC相关睡眠模式时钟控制宏定义 */
#define __ETHMAC_CLK_SLEEP_ENABLE  __HAL_RCC_ETHMAC_CLK_SLEEP_ENABLE // 使能以太网MAC睡眠模式时钟
#define __ETHMAC_CLK_SLEEP_DISABLE  __HAL_RCC_ETHMAC_CLK_SLEEP_DISABLE // 禁止以太网MAC睡眠模式时钟
#define __ETHMACTX_CLK_SLEEP_ENABLE  __HAL_RCC_ETHMACTX_CLK_SLEEP_ENABLE // 使能以太网MAC发送模块睡眠模式时钟
#define __ETHMACTX_CLK_SLEEP_DISABLE  __HAL_RCC_ETHMACTX_CLK_SLEEP_DISABLE // 禁止以太网MAC发送模块睡眠模式时钟
#define __ETHMACRX_CLK_SLEEP_ENABLE  __HAL_RCC_ETHMACRX_CLK_SLEEP_ENABLE // 使能以太网MAC接收模块睡眠模式时钟
#define __ETHMACRX_CLK_SLEEP_DISABLE  __HAL_RCC_ETHMACRX_CLK_SLEEP_DISABLE // 禁止以太网MAC接收模块睡眠模式时钟

/* 定时器12/13/14睡眠模式时钟控制宏定义 */
#define __TIM12_CLK_SLEEP_ENABLE  __HAL_RCC_TIM12_CLK_SLEEP_ENABLE // 使能TIM12睡眠模式时钟
#define __TIM12_CLK_SLEEP_DISABLE  __HAL_RCC_TIM12_CLK_SLEEP_DISABLE // 禁止TIM12睡眠模式时钟
#define __TIM13_CLK_SLEEP_ENABLE  __HAL_RCC_TIM13_CLK_SLEEP_ENABLE // 使能TIM13睡眠模式时钟
#define __TIM13_CLK_SLEEP_DISABLE  __HAL_RCC_TIM13_CLK_SLEEP_DISABLE // 禁止TIM13睡眠模式时钟
#define __TIM14_CLK_SLEEP_ENABLE  __HAL_RCC_TIM14_CLK_SLEEP_ENABLE // 使能TIM14睡眠模式时钟
#define __TIM14_CLK_SLEEP_DISABLE  __HAL_RCC_TIM14_CLK_SLEEP_DISABLE // 禁止TIM14睡眠模式时钟

/* 备份SRAM时钟控制宏定义 */
#define __BKPSRAM_CLK_ENABLE          __HAL_RCC_BKPSRAM_CLK_ENABLE // 使能备份SRAM时钟
#define __BKPSRAM_CLK_DISABLE          __HAL_RCC_BKPSRAM_CLK_DISABLE // 禁止备份SRAM时钟
#define __BKPSRAM_CLK_SLEEP_ENABLE  __HAL_RCC_BKPSRAM_CLK_SLEEP_ENABLE // 使能备份SRAM睡眠模式时钟
#define __BKPSRAM_CLK_SLEEP_DISABLE  __HAL_RCC_BKPSRAM_CLK_SLEEP_DISABLE // 禁止备份SRAM睡眠模式时钟

/* CCM数据RAM时钟控制宏定义 (Core Coupled Memory) */
#define __CCMDATARAMEN_CLK_ENABLE  __HAL_RCC_CCMDATARAMEN_CLK_ENABLE // 使能CCM数据RAM时钟
#define __CCMDATARAMEN_CLK_DISABLE  __HAL_RCC_CCMDATARAMEN_CLK_DISABLE // 禁止CCM数据RAM时钟

/* USART6通用同步/异步收发器时钟控制宏定义 */
#define __USART6_CLK_ENABLE          __HAL_RCC_USART6_CLK_ENABLE // 使能USART6时钟
#define __USART6_CLK_DISABLE          __HAL_RCC_USART6_CLK_DISABLE // 禁止USART6时钟
#define __USART6_FORCE_RESET        __HAL_RCC_USART6_FORCE_RESET // 强制复位USART6
#define __USART6_RELEASE_RESET        __HAL_RCC_USART6_RELEASE_RESET // 释放复位USART6
#define __USART6_CLK_SLEEP_ENABLE  __HAL_RCC_USART6_CLK_SLEEP_ENABLE // 使能USART6睡眠模式时钟
#define __USART6_CLK_SLEEP_DISABLE  __HAL_RCC_USART6_CLK_SLEEP_DISABLE // 禁止USART6睡眠模式时钟

/* SPI4串行外设接口时钟控制宏定义 */
#define __SPI4_CLK_ENABLE          __HAL_RCC_SPI4_CLK_ENABLE // 使能SPI4时钟
#define __SPI4_CLK_DISABLE          __HAL_RCC_SPI4_CLK_DISABLE // 禁止SPI4时钟
#define __SPI4_FORCE_RESET          __HAL_RCC_SPI4_FORCE_RESET // 强制复位SPI4
#define __SPI4_RELEASE_RESET        __HAL_RCC_SPI4_RELEASE_RESET // 释放复位SPI4
#define __SPI4_CLK_SLEEP_ENABLE   __HAL_RCC_SPI4_CLK_SLEEP_ENABLE // 使能SPI4睡眠模式时钟
#define __SPI4_CLK_SLEEP_DISABLE  __HAL_RCC_SPI4_CLK_SLEEP_DISABLE // 禁止SPI4睡眠模式时钟

/* GPIOI端口时钟控制宏定义 */
#define __GPIOI_CLK_ENABLE          __HAL_RCC_GPIOI_CLK_ENABLE // 使能GPIOI端口时钟
#define __GPIOI_CLK_DISABLE          __HAL_RCC_GPIOI_CLK_DISABLE // 禁止GPIOI端口时钟
#define __GPIOI_FORCE_RESET          __HAL_RCC_GPIOI_FORCE_RESET // 强制复位GPIOI端口
#define __GPIOI_RELEASE_RESET          __HAL_RCC_GPIOI_RELEASE_RESET // 释放复位GPIOI端口
#define __GPIOI_CLK_SLEEP_ENABLE  __HAL_RCC_GPIOI_CLK_SLEEP_ENABLE // 使能GPIOI睡眠模式时钟
#define __GPIOI_CLK_SLEEP_DISABLE  __HAL_RCC_GPIOI_CLK_SLEEP_DISABLE // 禁止GPIOI睡眠模式时钟

/* GPIOJ端口时钟控制宏定义 */
#define __GPIOJ_CLK_ENABLE          __HAL_RCC_GPIOJ_CLK_ENABLE // 使能GPIOJ端口时钟
#define __GPIOJ_CLK_DISABLE          __HAL_RCC_GPIOJ_CLK_DISABLE // 禁止GPIOJ端口时钟
#define __GPIOJ_FORCE_RESET         __HAL_RCC_GPIOJ_FORCE_RESET // 强制复位GPIOJ端口
#define __GPIOJ_RELEASE_RESET          __HAL_RCC_GPIOJ_RELEASE_RESET // 释放复位GPIOJ端口
#define __GPIOJ_CLK_SLEEP_ENABLE  __HAL_RCC_GPIOJ_CLK_SLEEP_ENABLE // 使能GPIOJ睡眠模式时钟
#define __GPIOJ_CLK_SLEEP_DISABLE  __HAL_RCC_GPIOJ_CLK_SLEEP_DISABLE // 禁止GPIOJ睡眠模式时钟

/* GPIOK端口时钟控制宏定义 */
#define __GPIOK_CLK_ENABLE          __HAL_RCC_GPIOK_CLK_ENABLE // 使能GPIOK端口时钟
#define __GPIOK_CLK_DISABLE          __HAL_RCC_GPIOK_CLK_DISABLE // 禁止GPIOK端口时钟
#define __GPIOK_RELEASE_RESET          __HAL_RCC_GPIOK_RELEASE_RESET // 释放复位GPIOK端口
#define __GPIOK_CLK_SLEEP_ENABLE  __HAL_RCC_GPIOK_CLK_SLEEP_ENABLE // 使能GPIOK睡眠模式时钟
#define __GPIOK_CLK_SLEEP_DISABLE  __HAL_RCC_GPIOK_CLK_SLEEP_DISABLE // 禁止GPIOK睡眠模式时钟

/* 以太网总体时钟控制宏定义 */
#define __ETH_CLK_ENABLE          __HAL_RCC_ETH_CLK_ENABLE // 使能以太网时钟
#define __ETH_CLK_DISABLE          __HAL_RCC_ETH_CLK_DISABLE // 禁止以太网时钟

/* DCMI数字摄像头接口时钟控制宏定义 */
#define __DCMI_CLK_ENABLE          __HAL_RCC_DCMI_CLK_ENABLE // 使能DCMI时钟
#define __DCMI_CLK_DISABLE          __HAL_RCC_DCMI_CLK_DISABLE // 禁止DCMI时钟
#define __DCMI_FORCE_RESET          __HAL_RCC_DCMI_FORCE_RESET // 强制复位DCMI
#define __DCMI_RELEASE_RESET          __HAL_RCC_DCMI_RELEASE_RESET // 释放复位DCMI
#define __DCMI_CLK_SLEEP_ENABLE   __HAL_RCC_DCMI_CLK_SLEEP_ENABLE // 使能DCMI睡眠模式时钟
#define __DCMI_CLK_SLEEP_DISABLE  __HAL_RCC_DCMI_CLK_SLEEP_DISABLE // 禁止DCMI睡眠模式时钟

/* UART7通用异步收发器时钟控制宏定义 */
#define __UART7_CLK_ENABLE          __HAL_RCC_UART7_CLK_ENABLE // 使能UART7时钟
#define __UART7_CLK_DISABLE          __HAL_RCC_UART7_CLK_DISABLE // 禁止UART7时钟
#define __UART7_RELEASE_RESET       __HAL_RCC_UART7_RELEASE_RESET // 释放复位UART7
#define __UART7_FORCE_RESET       __HAL_RCC_UART7_FORCE_RESET // 强制复位UART7
#define __UART7_CLK_SLEEP_ENABLE  __HAL_RCC_UART7_CLK_SLEEP_ENABLE // 使能UART7睡眠模式时钟
#define __UART7_CLK_SLEEP_DISABLE  __HAL_RCC_UART7_CLK_SLEEP_DISABLE // 禁止UART7睡眠模式时钟

/* UART8通用异步收发器时钟控制宏定义 */
#define __UART8_CLK_ENABLE          __HAL_RCC_UART8_CLK_ENABLE // 使能UART8时钟
#define __UART8_CLK_DISABLE          __HAL_RCC_UART8_CLK_DISABLE // 禁止UART8时钟
#define __UART8_FORCE_RESET          __HAL_RCC_UART8_FORCE_RESET // 强制复位UART8
#define __UART8_RELEASE_RESET          __HAL_RCC_UART8_RELEASE_RESET // 释放复位UART8
#define __UART8_CLK_SLEEP_ENABLE  __HAL_RCC_UART8_CLK_SLEEP_ENABLE // 使能UART8睡眠模式时钟
#define __UART8_CLK_SLEEP_DISABLE  __HAL_RCC_UART8_CLK_SLEEP_DISABLE // 禁止UART8睡眠模式时钟

/* USB OTG HS高速模式相关控制宏定义 */
#define __OTGHS_CLK_SLEEP_ENABLE  __HAL_RCC_USB_OTG_HS_CLK_SLEEP_ENABLE // 使能USB OTG HS睡眠模式时钟
#define __OTGHS_CLK_SLEEP_DISABLE  __HAL_RCC_USB_OTG_HS_CLK_SLEEP_DISABLE // 禁止USB OTG HS睡眠模式时钟
#define __OTGHS_FORCE_RESET          __HAL_RCC_USB_OTG_HS_FORCE_RESET // 强制复位USB OTG HS
#define __OTGHS_RELEASE_RESET          __HAL_RCC_USB_OTG_HS_RELEASE_RESET // 释放复位USB OTG HS
#define __OTGHSULPI_CLK_SLEEP_ENABLE  __HAL_RCC_USB_OTG_HS_ULPI_CLK_SLEEP_ENABLE // 使能USB OTG HS ULPI睡眠模式时钟
#define __OTGHSULPI_CLK_SLEEP_DISABLE  __HAL_RCC_USB_OTG_HS_ULPI_CLK_SLEEP_DISABLE // 禁止USB OTG HS ULPI睡眠模式时钟

/* USB OTG HS高速模式HAL库内部宏定义 */
#define __HAL_RCC_OTGHS_CLK_SLEEP_ENABLE  __HAL_RCC_USB_OTG_HS_CLK_SLEEP_ENABLE // 使能OTG HS睡眠模式时钟
#define __HAL_RCC_OTGHS_CLK_SLEEP_DISABLE  __HAL_RCC_USB_OTG_HS_CLK_SLEEP_DISABLE // 禁止OTG HS睡眠模式时钟
#define __HAL_RCC_OTGHS_IS_CLK_SLEEP_ENABLED __HAL_RCC_USB_OTG_HS_IS_CLK_SLEEP_ENABLED // 检查OTG HS睡眠模式时钟是否使能
#define __HAL_RCC_OTGHS_IS_CLK_SLEEP_DISABLED __HAL_RCC_USB_OTG_HS_IS_CLK_SLEEP_DISABLED // 检查OTG HS睡眠模式时钟是否禁止
#define __HAL_RCC_OTGHS_FORCE_RESET          __HAL_RCC_USB_OTG_HS_FORCE_RESET // 强制复位OTG HS
#define __HAL_RCC_OTGHS_RELEASE_RESET          __HAL_RCC_USB_OTG_HS_RELEASE_RESET // 释放复位OTG HS
#define __HAL_RCC_OTGHSULPI_CLK_SLEEP_ENABLE      __HAL_RCC_USB_OTG_HS_ULPI_CLK_SLEEP_ENABLE // 使能OTG HS ULPI睡眠模式时钟
#define __HAL_RCC_OTGHSULPI_CLK_SLEEP_DISABLE     __HAL_RCC_USB_OTG_HS_ULPI_CLK_SLEEP_DISABLE // 禁止OTG HS ULPI睡眠模式时钟
#define __HAL_RCC_OTGHSULPI_IS_CLK_SLEEP_ENABLED  __HAL_RCC_USB_OTG_HS_ULPI_IS_CLK_SLEEP_ENABLED // 检查OTG HS ULPI睡眠模式时钟是否使能
#define __HAL_RCC_OTGHSULPI_IS_CLK_SLEEP_DISABLED __HAL_RCC_USB_OTG_HS_ULPI_IS_CLK_SLEEP_DISABLED // 检查OTG HS ULPI睡眠模式时钟是否禁止

/* 其他外设睡眠模式时钟控制宏定义 */
#define __SRAM3_CLK_SLEEP_ENABLE       __HAL_RCC_SRAM3_CLK_SLEEP_ENABLE // 使能SRAM3睡眠模式时钟
#define __CAN2_CLK_SLEEP_ENABLE        __HAL_RCC_CAN2_CLK_SLEEP_ENABLE // 使能CAN2睡眠模式时钟
#define __CAN2_CLK_SLEEP_DISABLE       __HAL_RCC_CAN2_CLK_SLEEP_DISABLE // 禁止CAN2睡眠模式时钟
#define __DAC_CLK_SLEEP_ENABLE         __HAL_RCC_DAC_CLK_SLEEP_ENABLE // 使能DAC睡眠模式时钟
#define __DAC_CLK_SLEEP_DISABLE        __HAL_RCC_DAC_CLK_SLEEP_DISABLE // 禁止DAC睡眠模式时钟
#define __ADC2_CLK_SLEEP_ENABLE        __HAL_RCC_ADC2_CLK_SLEEP_ENABLE // 使能ADC2睡眠模式时钟
#define __ADC2_CLK_SLEEP_DISABLE       __HAL_RCC_ADC2_CLK_SLEEP_DISABLE // 禁止ADC2睡眠模式时钟
#define __ADC3_CLK_SLEEP_ENABLE        __HAL_RCC_ADC3_CLK_SLEEP_ENABLE // 使能ADC3睡眠模式时钟
#define __ADC3_CLK_SLEEP_DISABLE       __HAL_RCC_ADC3_CLK_SLEEP_DISABLE // 禁止ADC3睡眠模式时钟

/* FSMC可变静态存储控制器复位与睡眠时钟控制宏定义 */
#define __FSMC_FORCE_RESET             __HAL_RCC_FSMC_FORCE_RESET // 强制复位FSMC
#define __FSMC_RELEASE_RESET           __HAL_RCC_FSMC_RELEASE_RESET // 释放复位FSMC
#define __FSMC_CLK_SLEEP_ENABLE        __HAL_RCC_FSMC_CLK_SLEEP_ENABLE // 使能FSMC睡眠模式时钟
#define __FSMC_CLK_SLEEP_DISABLE       __HAL_RCC_FSMC_CLK_SLEEP_DISABLE // 禁止FSMC睡眠模式时钟

/* SDIO安全数字输入输出接口复位与睡眠时钟控制宏定义 */
#define __SDIO_FORCE_RESET             __HAL_RCC_SDIO_FORCE_RESET // 强制复位SDIO
#define __SDIO_RELEASE_RESET           __HAL_RCC_SDIO_RELEASE_RESET // 释放复位SDIO
#define __SDIO_CLK_SLEEP_DISABLE       __HAL_RCC_SDIO_CLK_SLEEP_DISABLE // 禁止SDIO睡眠模式时钟
#define __SDIO_CLK_SLEEP_ENABLE        __HAL_RCC_SDIO_CLK_SLEEP_ENABLE // 使能SDIO睡眠模式时钟

/* DMA2D图形加速器时钟控制宏定义 */
#define __DMA2D_CLK_ENABLE             __HAL_RCC_DMA2D_CLK_ENABLE // 使能DMA2D时钟
#define __DMA2D_CLK_DISABLE            __HAL_RCC_DMA2D_CLK_DISABLE // 禁止DMA2D时钟
#define __DMA2D_FORCE_RESET            __HAL_RCC_DMA2D_FORCE_RESET // 强制复位DMA2D
#define __DMA2D_RELEASE_RESET          __HAL_RCC_DMA2D_RELEASE_RESET // 释放复位DMA2D
#define __DMA2D_CLK_SLEEP_ENABLE       __HAL_RCC_DMA2D_CLK_SLEEP_ENABLE // 使能DMA2D睡眠模式时钟
#define __DMA2D_CLK_SLEEP_DISABLE      __HAL_RCC_DMA2D_CLK_SLEEP_DISABLE // 禁止DMA2D睡眠模式时钟

/* 为了兼容旧版本代码而保留的别名定义 */
#define __HAL_RCC_OTGFS_FORCE_RESET    __HAL_RCC_USB_OTG_FS_FORCE_RESET // 强制复位USB OTG FS (旧名称别名)
#define __HAL_RCC_OTGFS_RELEASE_RESET  __HAL_RCC_USB_OTG_FS_RELEASE_RESET // 释放复位USB OTG FS (旧名称别名)

/* ADC12/ADC34模数转换器时钟控制宏定义 (通常用于STM32F3系列) */
#define __ADC12_CLK_ENABLE          __HAL_RCC_ADC12_CLK_ENABLE // 使能ADC12时钟
#define __ADC12_CLK_DISABLE         __HAL_RCC_ADC12_CLK_DISABLE // 禁止ADC12时钟
#define __ADC34_CLK_ENABLE          __HAL_RCC_ADC34_CLK_ENABLE // 使能ADC34时钟
#define __ADC34_CLK_DISABLE         __HAL_RCC_ADC34_CLK_DISABLE // 禁止ADC34时钟

/* DAC2数模转换器时钟控制宏定义 */
#define __DAC2_CLK_ENABLE           __HAL_RCC_DAC2_CLK_ENABLE // 使能DAC2时钟
#define __DAC2_CLK_DISABLE          __HAL_RCC_DAC2_CLK_DISABLE // 禁止DAC2时钟

/* 定时器18/19/20时钟控制宏定义 */
#define __TIM18_CLK_ENABLE          __HAL_RCC_TIM18_CLK_ENABLE // 使能TIM18时钟
#define __TIM18_CLK_DISABLE         __HAL_RCC_TIM18_CLK_DISABLE // 禁止TIM18时钟
#define __TIM19_CLK_ENABLE          __HAL_RCC_TIM19_CLK_ENABLE // 使能TIM19时钟
#define __TIM19_CLK_DISABLE         __HAL_RCC_TIM19_CLK_DISABLE // 禁止TIM19时钟
#define __TIM20_CLK_ENABLE          __HAL_RCC_TIM20_CLK_ENABLE // 使能TIM20时钟
#define __TIM20_CLK_DISABLE         __HAL_RCC_TIM20_CLK_DISABLE // 禁止TIM20时钟

/* HRTIM1高分辨率定时器时钟控制宏定义 */
#define __HRTIM1_CLK_ENABLE         __HAL_RCC_HRTIM1_CLK_ENABLE // 使能HRTIM1时钟
#define __HRTIM1_CLK_DISABLE        __HAL_RCC_HRTIM1_CLK_DISABLE // 禁止HRTIM1时钟

/* SDADC1/2/3 sigma-delta模数转换器时钟控制宏定义 */
#define __SDADC1_CLK_ENABLE         __HAL_RCC_SDADC1_CLK_ENABLE // 使能SDADC1时钟
#define __SDADC2_CLK_ENABLE         __HAL_RCC_SDADC2_CLK_ENABLE // 使能SDADC2时钟
#define __SDADC3_CLK_ENABLE         __HAL_RCC_SDADC3_CLK_ENABLE // 使能SDADC3时钟
#define __SDADC1_CLK_DISABLE        __HAL_RCC_SDADC1_CLK_DISABLE // 禁止SDADC1时钟
#define __SDADC2_CLK_DISABLE        __HAL_RCC_SDADC2_CLK_DISABLE // 禁止SDADC2时钟
#define __SDADC3_CLK_DISABLE        __HAL_RCC_SDADC3_CLK_DISABLE // 禁止SDADC3时钟

/* ADC12/ADC34模数转换器复位控制宏定义 */
#define __ADC12_FORCE_RESET         __HAL_RCC_ADC12_FORCE_RESET // 强制复位ADC12
#define __ADC12_RELEASE_RESET       __HAL_RCC_ADC12_RELEASE_RESET // 释放复位ADC12
#define __ADC34_FORCE_RESET         __HAL_RCC_ADC34_FORCE_RESET // 强制复位ADC34
#define __ADC34_RELEASE_RESET       __HAL_RCC_ADC34_RELEASE_RESET // 释放复位ADC34

/* DAC2数模转换器复位控制宏定义 */
#define __DAC2_FORCE_RESET          __HAL_RCC_DAC2_FORCE_RESET // 强制复位DAC2
#define __DAC2_RELEASE_RESET        __HAL_RCC_DAC2_RELEASE_RESET // 释放复位DAC2

/* 定时器18/19/20复位控制宏定义 */
#define __TIM18_FORCE_RESET         __HAL_RCC_TIM18_FORCE_RESET // 强制复位TIM18
#define __TIM18_RELEASE_RESET       __HAL_RCC_TIM18_RELEASE_RESET // 释放复位TIM18
#define __TIM19_FORCE_RESET         __HAL_RCC_TIM19_FORCE_RESET // 强制复位TIM19
#define __TIM19_RELEASE_RESET       __HAL_RCC_TIM19_RELEASE_RESET // 释放复位TIM19
#define __TIM20_FORCE_RESET         __HAL_RCC_TIM20_FORCE_RESET // 强制复位TIM20
#define __TIM20_RELEASE_RESET       __HAL_RCC_TIM20_RELEASE_RESET // 释放复位TIM20

/* HRTIM1高分辨率定时器复位控制宏定义 */
#define __HRTIM1_FORCE_RESET        __HAL_RCC_HRTIM1_FORCE_RESET // 强制复位HRTIM1
#define __HRTIM1_RELEASE_RESET      __HAL_RCC_HRTIM1_RELEASE_RESET // 释放复位HRTIM1

/* SDADC1/2/3 sigma-delta模数转换器复位控制宏定义 */
#define __SDADC1_FORCE_RESET        __HAL_RCC_SDADC1_FORCE_RESET // 强制复位SDADC1
#define __SDADC2_FORCE_RESET        __HAL_RCC_SDADC2_FORCE_RESET // 强制复位SDADC2
#define __SDADC3_FORCE_RESET        __HAL_RCC_SDADC3_FORCE_RESET // 强制复位SDADC3
#define __SDADC1_RELEASE_RESET      __HAL_RCC_SDADC1_RELEASE_RESET // 释放复位SDADC1
#define __SDADC2_RELEASE_RESET      __HAL_RCC_SDADC2_RELEASE_RESET // 释放复位SDADC2
#define __SDADC3_RELEASE_RESET      __HAL_RCC_SDADC3_RELEASE_RESET // 释放复位SDADC3
